### ISSUE TITLE
Alpha 1.3.0 broke previous version, freezes in opening file location for roms and bios.

### ISSUE THREAD

**Issue by OniKyanAE86** [rafaelvcaetano/melonDS-android#10]
The newest alpha v1.3.0 broke previous version on all my devices. With v1.2.1 installed, installing 1.3.0 over v1.2.1 allows the app to open, but when selecting the location of the bios or roms, the application freezes then crashes. If MelonDS is uninstalled first from the device and then v1.3.0 is installed, when the emulator is run, it starts to load and immediately crashes and will not run on all my devices.

**Comment by rafaelvcaetano** [comment]
So, apparently the build I made had code changes that were supposed to be discarded. It was an initial effort to fix #7 (also opened by you) but I've decided to postpone them since major changes are required to support the upcoming Android 11. Guess I should setup CI to avoid problems like this.

**Comment by rafaelvcaetano** [comment]
I've attempted to fix this in release [Alpha 1.3.1](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/alpha-1.3.1). Could you see if the app no longer crashes? Be aware that external storage is still unsupported.

**Comment by rafaelvcaetano** [comment]
Closed due to lack of feedback.
