### ISSUE TITLE
DsiWare Manager not working

### ISSUE THREAD

**Issue by ghost** [rafaelvcaetano/melonDS-android#1026]
Device model:SM-A125M
Android version:11
Problem:
DsiWare manager does not work.when installing titles to NAND it crashes.When opening a nand with any titles in it it also crashes
Steps to reproduce (if applicable)
1. Open DSiWare Manager
2. Try Installing any Dsiware
3.it will instantly crash and DSiWare wont install
Issue is present in latest build
https://github.com/rafaelvcaetano/melonDS-android/actions/runs/3624682741

**Comment by rafaelvcaetano** [comment]
Please try the latest nightly build to see if this issue is fixed: https://github.com/rafaelvcaetano/melonDS-android/actions/runs/3788882532

**Comment by Starlightbotanist** [comment]
Thanks for this, there dsiware manager is working for me now. I never thought we would see this on Android.
