### ISSUE TITLE
Can't compile!! I have not idea!!

### ISSUE THREAD

**Issue by lishaoxia1985** [rafaelvcaetano/melonDS-android#1028]
The message is this:
```
null cannot be cast to non-null type kotlin.String
null cannot be cast to non-null type kotlin.String

Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

Re-download dependencies and sync project (requires network)
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.

Stop Gradle build processes (requires restart)
Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
```

**Comment by ipkpjersi** [comment]
I had this issue at one point but can't remember how I fixed it, if you're building this on Linux check out #1012 as that's what ended up in getting me a successful compile.

**Comment by rafaelvcaetano** [comment]
Sorry for the delay in the response! The most likely problem is that you don't have the keystore properties setup. I really need to update the README with these steps. But anyway, here is what you need to do:

* Open the `local.properties` file that is located in the project's root directory
* Add the following lines:

```
MELONDS_KEYSTORE=<path_to_keystore_file>
MELONDS_KEYSTORE_PASSWORD=<keystore_password>
MELONDS_KEY_ALIAS=<key_alias>
MELONDS_KEY_PASSWORD=<key_password>
```

Obviously, you need to replace the placeholders surrounded by `<>` with the proper values. They must be filled with keystore information and you have 2 options: create your own one OR use the debug one.

Creating a new one is hard to explain here, so it's better to look at some online documentation or tutorials. Here is an example of a StackOverflow post that shows multiple ways of doing it: https://stackoverflow.com/questions/3997748/how-can-i-create-a-keystore

Alternatively, you can use the debug keystore. Each Android SDK installation comes with a keystore that is used to create debug builds. If you want to use it, you can replace the placeholders above with the following values:
* `<path_to_keystore_file>`: Varies depending on OS. For Windows, it's: `C:\Users\USERNAME\.android\debug.keystore`. Replace `USERNAME` with your PC's username
* `<keystore_password>`: android
* `<key_alias>`: androiddebugkey
* `<key_password>`: android

Let me know if this works for you or if you need additional help!

**Comment by lishaoxia1985** [comment]
@rafaelvcaetano OK, I will try what you said.

**Comment by lishaoxia1985** [comment]
@rafaelvcaetano You should edit the readme.md and give some messages that how to compile the code
