### ISSUE TITLE
What is it?

### ISSUE THREAD

**Issue by NIPEL05** [rafaelvcaetano/melonDS-android#1081]
<font class="papago-parent"><font class="papago-source" style="display:none;">* **Device model:</font>* **디바이스 모델:</font><font class="papago-parent"><font class="papago-source" style="display:none;">** SM-N971N
</font>** SM-N971N</font><font class="papago-parent"><font class="papago-source" style="display:none;">* **Android version:</font>* **안드로이드 버전:</font><font class="papago-parent"><font class="papago-source" style="display:none;">** Android API 28
</font>** Android API 28</font><font class="papago-parent"><font class="papago-source" style="display:none;">* **melonDS version:</font>* **melonDS 버전:</font><font class="papago-parent"><font class="papago-source" style="display:none;">** Beta 1.7.0 GH
</font>** 베타 1.7.0 GH</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;">**Problem:</font>**문제:</font><font class="papago-parent"><font class="papago-source" style="display:none;">**  
</font>**</font><font class="papago-parent"><font class="papago-source" style="display:none;">Insert a small description of the problem.</font>문제에 대한 간단한 설명을 삽입합니다.</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;">**Stack trace:</font>**스택 트레이스:</font><font class="papago-parent"><font class="papago-source" style="display:none;">**  
</font>**</font><font class="papago-parent"><font class="papago-source" style="display:none;">```
</font>```</font><font class="papago-parent"><font class="papago-source" style="display:none;">j6.c: Could not create temporary SRAM file at content://com.android.providers.downloads.documents/tree/downloads/document/downloads
</font>j6.c: content://com.android.providers.downloads.downloads.documents/tree/downloads/documents/downloads에서 임시 SRAM 파일을 생성할 수 없습니다.</font><font class="papago-parent"><font class="papago-source" style="display:none;">	at me.magnum.melonds.ui.emulator.</font>magnum.melonds.ui.에뮬레이터에 접속합니다.</font><font class="papago-parent"><font class="papago-source" style="display:none;">EmulatorViewModel.</font>에뮬레이터 뷰 모델</font><font class="papago-parent"><font class="papago-source" style="display:none;">N(Unknown Source:117)
</font>N(출처 불명:117)</font><font class="papago-parent"><font class="papago-source" style="display:none;">	at n6.q.</font>n6.q.에.</font><font class="papago-parent"><font class="papago-source" style="display:none;">N(Unknown Source:75)
</font>N(출처 불명:75)</font><font class="papago-parent"><font class="papago-source" style="display:none;">	at n6.q.x(Unknown Source:0)
</font>n6.q.x (알 수 없는 소스:0)</font><font class="papago-parent"><font class="papago-source" style="display:none;">	at n6.p.a(Unknown Source:8)
</font>n6.p.a (출처 불명:8)</font><font class="papago-parent"><font class="papago-source" style="display:none;">	at b4.a.v(Unknown Source:10)
</font>b4.a.v(출처 불명:10)로</font><font class="papago-parent"><font class="papago-source" style="display:none;">	at m3.u.b(Unknown Source:14)
</font>m3.u.b (출처 불명:14)</font><font class="papago-parent"><font class="papago-source" style="display:none;">	at b4.f$a.d(Unknown Source:27)
</font>b4.f$a.d (출처 불명:27)</font><font class="papago-parent"><font class="papago-source" style="display:none;">	at b4.p$b.c(Unknown Source:26)
</font>b4.p$b.c (출처 불명:26)</font><font class="papago-parent"><font class="papago-source" style="display:none;">	at b4.p$c.d(Unknown Source:4)
</font>b4.p$c.d (알 수 없는 소스:4)</font><font class="papago-parent"><font class="papago-source" style="display:none;">	at y3.m$a.d(Unknown Source:6)
</font>y3.m$a.d(출처 불명:6)</font><font class="papago-parent"><font class="papago-source" style="display:none;">	at y3.j$a.run(Unknown Source:21)
</font>y3.j$a.run (출처 불명:21)</font><font class="papago-parent"><font class="papago-source" style="display:none;">	at m3.t$a.run(Unknown Source:9)
</font>m3.t$a.run (출처 불명:9)</font><font class="papago-parent"><font class="papago-source" style="display:none;">	at d4.k.run(Unknown Source:13)
</font>d4.k.run (출처 불명:13)</font><font class="papago-parent"><font class="papago-source" style="display:none;">	at d4.k.call(Unknown Source:0)
</font>d4.k.call(알 수 없는 소스:0)에서</font><font class="papago-parent"><font class="papago-source" style="display:none;">	at java.util.concurrent.</font>동시에.</font><font class="papago-parent"><font class="papago-source" style="display:none;">FutureTask.run(FutureTask.java:266)
</font>FutureTask.run (FutureTask.java:266)</font><font class="papago-parent"><font class="papago-source" style="display:none;">	at java.util.concurrent.</font>동시에.</font><font class="papago-parent"><font class="papago-source" style="display:none;">Scheduled</font>스케줄 완료</font><font class="papago-parent"><font class="papago-source" style="display:none;">ThreadPoolExecutor$ScheduledFutureTask.run(Scheduled</font>ThreadPoolExecutor$ScheduledFutureTask.run(스케줄 완료)</font><font class="papago-parent"><font class="papago-source" style="display:none;">ThreadPoolExecutor.java:301)
</font>ThreadPoolExecutor.java:301)</font><font class="papago-parent"><font class="papago-source" style="display:none;">	at java.util.concurrent.</font>동시에.</font><font class="papago-parent"><font class="papago-source" style="display:none;">ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
</font>ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)</font><font class="papago-parent"><font class="papago-source" style="display:none;">	at java.util.concurrent.</font>동시에.</font><font class="papago-parent"><font class="papago-source" style="display:none;">ThreadPoolExecutor$</font>ThreadPoolExecutor$</font><font class="papago-parent"><font class="papago-source" style="display:none;">Worker.run(ThreadPoolExecutor.java:641)
</font>Worker.run(ThreadPoolExecutor.java:641)</font><font class="papago-parent"><font class="papago-source" style="display:none;">	at java.lang.</font>를 참조해 주세요.</font><font class="papago-parent"><font class="papago-source" style="display:none;">Thread.run(Thread.java:764)
</font>Thread.run (Thread.java:764)</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;">```
</font>```</font><font class="papago-parent"><font class="papago-source" style="display:none;">
</font>
</font><font class="papago-parent"><font class="papago-source" style="display:none;">**Configuration:</font>** 구성:</font><font class="papago-parent"><font class="papago-source" style="display:none;">**  
</font>**</font><font class="papago-parent"><font class="papago-source" style="display:none;">```
</font>```</font><font class="papago-parent"><font class="papago-source" style="display:none;">RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, showBootScreen=false, dsBios7</font>RomCrashContext(에뮬레이터 구성=에뮬레이터 구성 사용)(CustomBios=false, showBootScreen=false, dsBios7 사용)</font><font class="papago-parent"><font class="papago-source" style="display:none;">Uri=null, dsBios9</font>URI=프로세서, dsBios9</font><font class="papago-parent"><font class="papago-source" style="display:none;">Uri=null, dsFirmwareUri=null, dsiBios7</font>URI=module, dsFirmwareUri=module, dsiBios7</font><font class="papago-parent"><font class="papago-source" style="display:none;">Uri=null, dsiBios9</font>URI=프로세서, dsiBios9</font><font class="papago-parent"><font class="papago-source" style="display:none;">Uri=null, dsiFirmwareUri=null, dsiNandUri=null, internalDirectory=/data/user/150/com.trendmicro.tmas/sandboxdata/me.magnum.melonds/data/files, fastForwardSpeedMultiplier=-1.0, rewindEnabled=false, rewindPeriodSeconds=10, rewindWindowSeconds=60, useJit=true, console</font>Uri=sys, dsiFirmwareUri=sys, dsiNandUri=sys, internalDirectory=/data/user/150/com.trendmicro.tmas/sandboxdata/me.magnum.melonds/data/files, ForwardSpeedMultiplier=-1.0, rewindEnable=1.0, false, rewind, rewind=10, rewind, rewind, rewind.dow</font><font class="papago-parent"><font class="papago-source" style="display:none;">Type=DS, soundEnabled=true, audioInterpolation=</font>유형=DS, soundEnabled=true, audioInterpolation=</font><font class="papago-parent"><font class="papago-source" style="display:none;">NONE, audioBitrate=</font>없음, audioBitrate=</font><font class="papago-parent"><font class="papago-source" style="display:none;">AUTO, volume=256, audioLatency=MEDIUM, micSource=B</font>AUTO, 볼륨=256, audioLatency=MEDIUM, micSource=B</font><font class="papago-parent"><font class="papago-source" style="display:none;">LOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=</font>LOW, firmwareConfiguration=MicrosoftConfiguration(닉네임=플레이어, 메시지=)</font><font class="papago-parent"><font class="papago-source" style="display:none;">Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1, randomizeMacAddress=false, internalMacAddress=00:09:</font>안녕하세요! language=1, favoriteColour=0, birthday=1, birthday=1, randomizeMacAddress=false, internalMacAddress=00:09:</font><font class="papago-parent"><font class="papago-source" style="display:none;">BF:C9:EF:</font>BF:C9:EF:</font><font class="papago-parent"><font class="papago-source" style="display:none;">EB), rendererConfiguration=RendererConfiguration(videoFiltering=</font>EB), renderer Configuration=Renderer Configuration(video Filtering=)</font><font class="papago-parent"><font class="papago-source" style="display:none;">LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.providers.downloads.documents/tree/downloads, romUri=content://com.android.providers.downloads.documents/tree/downloads/document/7188, sramUri=null)
</font>LINEAR, snadedRendering=true)) romSearchDirUri=콘텐츠://com.android.providers.downloads/tree/downloads/documents/7,sUriRam=content)</font><font class="papago-parent"><font class="papago-source" style="display:none;">```
</font>```</font>

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.
