### ISSUE TITLE
Google Drive Sync!

### ISSUE THREAD

**Issue by ASGAMING009** [rafaelvcaetano/melonDS-android#1086]
Pretty Self Explanatory. Google Drive Sync For save files like My Boy [Gba Emulator].

**Comment by rafaelvcaetano** [comment]
I'm going to close this because it's a duplicate of #277. I know that it's a pretty old issue, but I haven't forgotten about it 😛

**Comment by ASGAMING009** [comment]
Wow

**Comment by ASGAMING009** [comment]
🤣k bro
