### ISSUE TITLE
Added GBA Rom issue

### ISSUE THREAD

**Issue by HJMBgit84** [rafaelvcaetano/melonDS-android#11]
When you said added GBA Rom you mean to be able to play gba games? I tried to play them and not possible so far

**Comment by rafaelvcaetano** [comment]
No. By GBA ROM support I mean that it's possible for NDS ROMs to interact with GBA ROMs (like how Pokémon games can migrate from GBA cartridges). Support to actually run GBA ROMs is not expected.

**Comment by HJMBgit84** [comment]
Oh I see ok, thanks and keep this project alive please :)
