### ISSUE TITLE
Pokémon SoulSilver

### ISSUE THREAD

**Issue by Dan945** [rafaelvcaetano/melonDS-android#110]
* **Device model:** Redmi 6A
* **Android version:** Android API 27

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$f: Failed to load ROM: NDS_FAILED
	at me.magnum.melonds.ui.emulator.j$c$a$a.a(Unknown Source:205)
	at f.a.b0.e.e.a.m(Unknown Source:10)
	at f.a.s.a(Unknown Source:14)
	at f.a.b0.e.b.e$a.d(Unknown Source:26)
	at f.a.b0.e.b.l$a.d(Unknown Source:2)
	at f.a.b0.e.b.j$a.run(Unknown Source:21)
	at f.a.r$a.run(Unknown Source:9)
	at f.a.b0.g.j.run(Unknown Source:13)
	at f.a.b0.g.j.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

```

**Comment by Dan945** [comment]
Esta cosa no me deja jugar ;-;

**Comment by rafaelvcaetano** [comment]
Pero abrir 3 problemas iguales no va a solucionar nada. Se está averiguando el problema y será corregido en la próxima versión. Mientras tanto intenta una de estas soluciones:

* Colocar las ROM y los ficheros de BIOS en el almacenamiento interno
* Intentar una BIOS diferente
* Hacer una cópia del fichero `firmware.bin` (en la misma carpeta) y nombrarlo de `firmware.bin.bak`

**Comment by Dan945** [comment]
Este sí gracias, pero es que no entendí bien que toca hacer 😅

**Comment by rafaelvcaetano** [comment]
Haber. Donde pusiste tus ROMs y ficheros de BIOS? En el almacenamiento interno? O en una tarjeta SD?

**Comment by Dan945** [comment]
En el almacenamiento interno

**Comment by rafaelvcaetano** [comment]
Entonces, haz lo siguiente:

- Anda a la carpeta en donde pusiste los ficheros de BIOS
- Copia el fichero `firmware.bin`
- En la misma capeta, pega el fichero
- Nombra la nueva cópia del fichero a `firmware.bin.bak`

**Comment by Dan945** [comment]
Ok y ahora que?

**Comment by rafaelvcaetano** [comment]
Intenta jugar una ROM. Y dime como te va.

**Comment by Dan945** [comment]
Este aún no me deja y hice todo lo que me enviaste

**Comment by rafaelvcaetano** [comment]
Envíame un screenshot de la carpeta en donde están los ficheros de BIOS.

**Comment by Dan945** [comment]
Perdón por tardar 😥

**Comment by rafaelvcaetano** [comment]
No sé si intentaste enviar el screenshot por e-mail, pero no eh recibido nada. Si lo hiciste, puedes intentar de nuevo? Pero esta vez subiendo directamente por GitHub y no por correo.

**Comment by Dan945** [comment]
![Screenshot_2021-02-24-15-51-45-058_com.mi.android.globalFileexplorer.png](https://user-images.githubusercontent.com/79588892/109172533-caf98e00-777a-11eb-9cc8-0290e0be9c7b.png)

**Comment by rafaelvcaetano** [comment]
Creo que algo no está bien con esa BIOS. Me puedes enviar un screenshot de la pantalla de Settings, en la sección "System"?

**Comment by Dan945** [comment]
![Screenshot_2021-02-25-10-17-02-031_me.magnum.melonds.png](https://user-images.githubusercontent.com/79588892/109174253-9555a480-777c-11eb-8ff6-32b24e79e00b.png)@rafaelvcaetano

**Comment by rafaelvcaetano** [comment]
En donde dice "DS BIOS Directory", el camino no está bien. Y la verdad no sé porque no sale ningún error. En esa opción deves escoger la carpeta en donde tienes los ficheros de BIOS. Si después de cambiar te sale igual, entonces mueve esa carpeta afuera de la carpeta "Download" y escoge el camino de nuevo.

**Comment by shabbirmahmud** [comment]
> ![Screenshot_2021-02-25-10-17-02-031_me.magnum.melonds.png](https://user-images.githubusercontent.com/79588892/109174253-9555a480-777c-11eb-8ff6-32b24e79e00b.png)

I saw this weird directory when i was tried to clone the emulator in work profile.Bt after clearing data and select the directory again i solved this problem.

**Comment by shabbirmahmud** [comment]
Try the new [beta v1.2.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.2.2) release and check if it's solve the problem?

**Comment by shabbirmahmud** [comment]
Can you use the latest beta [v1.3.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.3.0) and open a new issue? The latest version does not fix the problem but includes additional info that will help to find the cause.

**Comment by rafaelvcaetano** [comment]
If your problem is not yet fixed, try the latest [Beta 1.4.0](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) release. If the problem is not fixed, please open a new issue.
