### ISSUE TITLE
DS Bios Wont Work

### ISSUE THREAD

**Issue by SkylineUset** [rafaelvcaetano/melonDS-android#1106]
* **Device model:** SM-G973U
* **Android version:** Android API 31
* **melonDS version:** Beta 1.8.0 PS

**Problem:**  
DS Bios Won't Work After Pressing the button to launch the DS

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.
