### ISSUE TITLE
Gen 5 GTS Doens't Work

### ISSUE THREAD

**Issue by ASGAMING009** [rafaelvcaetano/melonDS-android#1116]
In Gen 4 GTS and some Other stuff Works... On the other hand in Gen 5 only Mystery Gift is Working And anything else just gets Some error....
Sidenote GTS NEGATION DOES WORK and also Wifi club ALSO Work Tried With 2 devices Not Stable But yeah.....

**Comment by Swappo91** [comment]
rafael actually dont want to try to fix netplay. damn.
Thats the best feature of melonds emu and doesnt work...

**Comment by rafaelvcaetano** [comment]
The latest version has added proper support for Wi-Fi connectivity. It should be much more stable now. I'll close this issue and feel free to open a new one if you have some specific issue.
