### ISSUE TITLE
.

### ISSUE THREAD

**Issue by nigoji** [rafaelvcaetano/melonDS-android#1142]
* **Device model:** <V2154>
* **Android version:** <13 tiramisu>

**Problem: failed to load a game **  

![IMG_20230405_232934.jpg](https://user-images.githubusercontent.com/116516920/230651419-8e3a3f6a-bd61-43bc-ac6c-ebb8ef4151bc.jpg)

the game works fine,But emulator can't turn them idk why

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.
