### ISSUE TITLE
problems when opening the games or when entering the retroarchievements menu

### ISSUE THREAD

**Issue by Seaofstars86** [rafaelvcaetano/melonDS-android#1143]
*Device model: Moto G60
*Android version: Android 12

*Problem:I have a problem regarding the new nighty release, the one called save retroarchievements state in savestates. What happens is that since I downloaded that version, when I try to play a game or when I enter the retroarchievements part, the emulator closes or restarts that would be the only problem in this nighty release

**Comment by rafaelvcaetano** [comment]
Please try the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) where this problem should be fixed. Or download it from the [Play Store](https://play.google.com/store/apps/details?id=me.magnum.melonds) to always keep the app up-to-date. If you still encounter errors after updating, please open a new issue.
