### ISSUE TITLE
This Feature is not working on redmi 5 plus and realme 5i

### ISSUE THREAD

**Issue by shabbirmahmud** [rafaelvcaetano/melonDS-android#115]
![Screenshot_20210226-085702_melonDS](https://user-images.githubusercontent.com/47573399/109248854-d3040d00-7810-11eb-9aa9-b8a39fcbf26d.png)
I tried to open this feature in my phone bt every time I pressed this feature the emulator crashed.
Here is the crash log url-https://del.dog/iregnurequ

https://user-images.githubusercontent.com/47573399/109252577-1d3cbc80-7818-11eb-8a95-6d37b27764ea.mp4

https://user-images.githubusercontent.com/47573399/109253024-0f3b6b80-7819-11eb-93c9-00d0ddd2bcac.mp4

**Comment by rafaelvcaetano** [comment]
Oh well, damn Android and its release builds. I will release a hotfix tonight.

**Comment by rafaelvcaetano** [comment]
A hotfix has been released in version [Beta 1.2.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.2.2).

**Comment by shabbirmahmud** [comment]
> A hotfix has been released in version [Beta 1.2.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.2.2).

Yeah the hotfix version beta 1.2.2 has solved the problem.You can close this

**Comment by shabbirmahmud** [comment]
> > A hotfix has been released in version [Beta 1.2.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.2.2).
> 

Yeah the hotfix version beta 1.2.2 has solved the problem in both phobe.You can close this issue.
