### ISSUE TITLE
Compressed rom(Zip files) images are not showing properly 

### ISSUE THREAD

**Issue by shabbirmahmud** [rafaelvcaetano/melonDS-android#116]
Device-Redmi 5+ & Realme 5i

![Screenshot_2021-02-26-09-04-03-69_e7877f9796c3bfb5a5339f6b3513bed1](https://user-images.githubusercontent.com/47573399/109249473-f5e2f100-7811-11eb-9682-dfb6c392c45e.jpg)
![Screenshot_20210301-144301_melonDS](https://user-images.githubusercontent.com/47573399/109472557-774db400-7a9c-11eb-9808-77989ff68fb0.png)

**Comment by rafaelvcaetano** [comment]
Does this happen only for ZIP files? If you extract a ROM, does the icon appear correctly?

**Comment by shabbirmahmud** [comment]
> Does this happen only for ZIP files? If you extract a ROM, does the icon appear correctly?

Yes if i extract a rom the icon appear correctly.

**Comment by shabbirmahmud** [comment]
I think not all rom has this problem.I have super mario bros game.Even it is in the zip formate the icon is showing properly.

![Screenshot_2021-03-14-19-50-50-24_e7877f9796c3bfb5a5339f6b3513bed1](https://user-images.githubusercontent.com/47573399/111071111-d2e95a00-84fe-11eb-9e71-1202ad7c2792.jpg)

**Comment by rafaelvcaetano** [comment]
This problem is inconsistent. If you try to clear your app's cache (only the cache, not all the data), I'm pretty sure you will have different outcomes. Some icons will be OK, others won't.

**Comment by shabbirmahmud** [comment]
I cleared the app cache bt the result is still same.

![Screenshot_2021-03-14-21-04-42-17_e7877f9796c3bfb5a5339f6b3513bed1](https://user-images.githubusercontent.com/47573399/111073462-016c3280-8509-11eb-89cd-20e4c1d27829.jpg)

**Comment by shabbirmahmud** [comment]
Maybe this can solve the problem by making a icon cache like this on drastic ds emulator-

![Screenshot_2021-03-15-01-43-20-32](https://user-images.githubusercontent.com/47573399/111082056-799a1e80-8530-11eb-9aeb-5f378d91f0ed.jpg)

**Comment by shabbirmahmud** [comment]
After deleting the icon cache the icon is showing prop

**Comment by shabbirmahmud** [comment]
When the rom was unzipped I deleted the icon cache in the android folder.Then i close the emulator and open again.The icon is showing properly now.Thanks to #252.
Clearing cache didn't work coz ig it also clear the uzipped rom.

![Screenshot_2021-03-27-22-56-07-65](https://user-images.githubusercontent.com/47573399/112728599-4b660700-8f52-11eb-9e25-2d91f00974f3.jpg)
![Screenshot_2021-03-27-22-55-54-91](https://user-images.githubusercontent.com/47573399/112728605-502abb00-8f52-11eb-8a5e-2fd7847f43ff.jpg)

**Comment by rafaelvcaetano** [comment]
This should be fixed in the [Beta 1.5.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.0) release.

**Comment by shabbirmahmud** [comment]
> This should be fixed in the [Beta 1.5.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.0) release.

Icons are now showing properly without clearing icon_cache.Thank u so much for your hard work ☺️☺️.
