### ISSUE TITLE
Can't play DSI games.

### ISSUE THREAD

**Issue by dreamboyn81** [rafaelvcaetano/melonDS-android#117]
I downloaded nearly 700 DSI games, and few of them can play except the ones that come with the system.
Opening is all error messages. Have you organized a list of playable games? It is really troublesome to try one by one. I have updated it many times, each time it is the same problem.
![Screenshot_20210226_122017_me magnum melonds](https://user-images.githubusercontent.com/15012771/109254846-ccd05980-782d-11eb-9fa2-fdbb51a44964.jpg)

**Comment by shabbirmahmud** [comment]
Dsi has some serious problem.I don't know much about it

**Comment by haojiezhu** [comment]
melonDS can't load DSiWare roms directly. They need to be installed on the NAND.
https://github.com/rafaelvcaetano/melonDS-android/issues/44

Someone wrote a tool called "DSiWare to NAND Package" for that.
https://gbatemp.net/threads/dsiware-to-nand-package-a-tool-to-help-you-with-adding-dsiware-to-your-nand.580469/

**Comment by dreamboyn81** [comment]
> melonDS无法直接加载DSiWare rom。它们需要安装在NAND上。参见问题[＃44](https://github.com/rafaelvcaetano/melonDS-android/issues/44)。
> 
> 有人创建了一个名为“ DSiWare to NAND Package”的软件包，以略微简化此过程。
> https://gbatemp.net/threads/dsiware-to-nand-package-a-tool-to-help-you-with-adding-dsiware-to-your-nand.580469/

Thanks for sharing, I will try🥰.

**Comment by dreamboyn81** [comment]
![Screenshot_20210228_164405_me magnum melonds](https://user-images.githubusercontent.com/15012771/109412680-52960580-79e4-11eb-8f9c-daf0eb90e2aa.jpg)
I succeeded, so troublesome.
Everything else is fine, only Zelda can't play it.

**Comment by haojiezhu** [comment]
> I succeeded, so troublesome.
> Everything else is fine, only Zelda can't play it.

To play Zelda, you need to turn off "Enable JIT" in melonDS settings. Some games still won't work even with "Enable JIT" off, like "WarioWare: Snapped!". Have to wait for improvement of DSi game compatibility.

**Comment by dreamboyn81** [comment]
![Screenshot_20210228_164405_me magnum melonds](https://user-images.githubusercontent.com/15012771/109430749-daf4c480-7a3d-11eb-91c3-2fe52e76314a.jpg)

**Comment by dreamboyn81** [comment]
> > 我成功了，真麻烦。
> > 其他一切都很好，只有Zelda不能玩。
> 
> 要播放Zelda，您需要在melonDS设置中关闭“启用JIT”。即使关闭“启用JIT”，某些游戏仍然无法正常工作，例如“ WarioWare：Snapped！”。必须等待DSi游戏兼容性的提高。

Thanks, I can play Zelda🥳.
It would be better if the simulator was updated to add horizontal screen and filters☺️.

**Comment by rafaelvcaetano** [comment]
> Thanks, I can play Zelda🥳.
> It would be better if the simulator was updated to add horizontal screen and filters☺️.

In development 😉

**Comment by rafaelvcaetano** [comment]
Since the major problems have been addressed, I will close this issue. Feel free to open another one if you think something is still missing.
