### ISSUE TITLE
MelonDS 1.8.0 Update Wireless Connection Issue

### ISSUE THREAD

**Issue by ShipperNessity** [rafaelvcaetano/melonDS-android#1170]
The latest update's Wireless Connection feature doesn't work well, when doing the Dual App feature on phone. When you use Double Screen feature on Android, even on pictochats it doesn't work. But when I installed the 1.7.0 version, it works fine. I tried switching on and off the Randomized MAC Address setting, but still no luck for 1.8.0.

* **Device model:** <insert your device's model here>
* **Android version:** <insert your device's Android version here>

**Problem:**  
Write a small description of the problem.

**Steps to reproduce (if applicable):**
1. Write a list of steps
2. Required for the problem
3. To appear

Add screenshots if the issue can be visualized.

**Comment by ShipperNessity** [comment]
Device model: Poco F2 Pro

Android version: Android 12, MIUI 14.0.1

**Comment by DaXcess** [comment]
Still happening on (almost) latest nightly build (d905d0082b069f9a82e39215aae819488d8fe715, couldn't try the absolute newest as it immediately crashes).

Did some debugging using PCAPDroid and saw 0 traffic during online connection attempts (local multiplayer, WFC works fine). Downgraded to 1.7.0 and saw UDP network traffic (however multiplayer on 0.9.3 is 100% unplayable).

Device Model: Samsung Note 10 Lite
Android 13, OneUI 5.1

**Comment by rafaelvcaetano** [comment]
Sorry for the late reply. Unfortunately, local multiplayer doesn't work since Beta 1.8.0. You can read more about it here: https://github.com/rafaelvcaetano/melonDS-android/issues/1230#issuecomment-1792524556

Meanwhile, if you want to use that feature, you will have to continue with Beta 1.7
