### ISSUE TITLE
Crash when launching a game on latest nightly

### ISSUE THREAD

**Issue by Someguy1519** [rafaelvcaetano/melonDS-android#1191]
* **Device model:** SM-S906U
* **Android version:** 13

**Problem:**  
Latest nightly crashes when launching a game

**Steps to reproduce (if applicable):**
1. Try to launch a game on MelonDS 4d4d667
2. Crashes instantly 
3. 

Add screenshots if the issue can be visualized.

![Screenshot_20230809_184953_Device care](https://github.com/rafaelvcaetano/melonDS-android/assets/27980228/ba82c09a-98fa-4130-9344-b0f0bb0afdbf)

**Comment by rafaelvcaetano** [comment]
Sorry about that. Please try the latest nightly build, which should have fixed this issue. If not, let me know again 🙂

**Comment by rafaelvcaetano** [comment]
That I cannot reproduce. Sorry for asking this, but can you try clearing the app data? I know this is a bit frustrating, but I am not implementing proper conversions between nightly updates because it would take a lot of time, so sometimes it's necessary to clear the app data 😔
