### ISSUE TITLE
Crashing problem in latest Nightly Build

### ISSUE THREAD

**Issue by cat-gardield** [rafaelvcaetano/melonDS-android#1195]
* **Device model:** SM-A546E
* **Android version:** 13

**Problem:**  
In the latest Nightly Build, when trying to emulate the DS/DSi BIOS or when trying to open any ROM; the emulator crashes

(P.S: the ROMS list & everything else is running correctly, except when trying to emulate the DS/DSi BIOS)

**Comment by rafaelvcaetano** [comment]
Should be fixed now. Give the latest nightly build a try

**Comment by cat-gardield** [comment]
> Should be fixed now. Give the latest nightly build a try

Yep, it works perfectly now. Thanks!
