### ISSUE TITLE
Online Support gone

### ISSUE THREAD

**Issue by AGESdotJPEG** [rafaelvcaetano/melonDS-android#1236]
* **Device model:** <Galaxy A52s 5G>
* **Android version:** <13>

**Problem:**  
Version 1.9.1 broke the online functions precious version added and now not even the connection test function works nor the DSi Web Browser

**Steps to reproduce (if applicable):**
1. Use version 1.9.1
2. Do any online action
3. Error 52200 or 52201 will always appear

Add screenshots if the issue can be visualized.
1.9.0: https://media.discordapp.net/attachments/815586562083520556/1171641006190514176/Screenshot_20231107_204231_melonDS.jpg?ex=655d6ab7&is=654af5b7&hm=5e4c0976cf54e8914cf4c7dfb88f17e19486d3093630fc22ac12de0d01687a59&
1.9.1: https://media.discordapp.net/attachments/815586562083520556/1171641082770116668/Screenshot_20231107_203947_melonDS.jpg?ex=655d6aca&is=654af5ca&hm=b15c2d863222b9a17852315cd6862816ba130c401737669d41f0e014d783d4eb&

**Comment by rafaelvcaetano** [comment]
I assume you are using Kaeru WFC. There must be something wrong on their DNS server because the issue is also happening on my real DS system.

![image](https://github.com/rafaelvcaetano/melonDS-android/assets/9086379/736f7047-c6be-4c16-a537-6a7ccae041ce)

**Comment by AGESdotJPEG** [comment]
Oof

**Comment by MichaelNA2005** [comment]
You have to use RiiConnect24 DNS (167.86.108.126) as the primary one, and then any other DNS (like 8.8.8.8) as the secondary one.

**Comment by rafaelvcaetano** [comment]
The guys at Kaeru WFC have solve the issue, so it's back to normal.

**Comment by Dwaqter** [comment]
But could it already be working in games?

**Comment by rafaelvcaetano** [comment]
Yep. I tested it and it seems to be working fine.
