### ISSUE TITLE
I can't get achievements for Castlevania Portrait of Ruin

### ISSUE THREAD

**Issue by Seaofstars86** [rafaelvcaetano/melonDS-android#1237]
* **Device model:** Moto G60
* **Android version:** Android 12

**Problem:**  
I don't know if it is a problem with the page or the emulator but with the game Castlevania Portrait of Ruin I have tried to complete several achievements but even if they meet the requirements they are not unlocked At first I thought it was an error on the Retroachievements page but the achievements are unlocked correctly when playing in the retroarch emulator, And although I could try to unlock them in retroarch, at least on my retroarch device, all nds cores have very low performance and many bugs, so I would really appreciate it if you could fix that since I really appreciate all the work you have done ✨

**Comment by rafaelvcaetano** [comment]
Does this happen for all achievements? Or only for some of them?

**Comment by Seaofstars86** [comment]
Apparently it happens with everyone, since I have already tried to obtain several achievements among which are defeating Dracula without receiving damage and another which was to obtain all the records, At the moment it is the only game with which I have had that problem since in Shin Megami Tensei strange journey I have been able to unlock the achievements correctly

**Comment by rafaelvcaetano** [comment]
It seems to be working OK here. At least, the first achievement is always unlocking for me. Do you have some more advanced save files or save states that I can use to test other achievements?


https://github.com/rafaelvcaetano/melonDS-android/assets/9086379/7617a4fc-681e-490c-bce8-5ac614c3b7c1

**Comment by Seaofstars86** [comment]
If I have a save of my game it is already somewhat advanced, there is a game in which it is just before defeating Dracula and another one that is 1000% complete, how can I send it to you?

**Comment by Seaofstars86** [comment]
This I just reset the progress of one of the achievements, to see if it was unlocked and apparently they already work correctly and I just checked the Retroachievements page and I realized that when I tried to unlock it it was before the release of update 1.9.1, for which I want to apologize since it was my mistake not to having seen that detail 😿

**Comment by rafaelvcaetano** [comment]
Release 1.9.1 didn't introduce any change in the RetroAchievements implementation. Unless you were still on the 1.8.0 version. Anyway, there's always the possibility that you were offline when you were playing at that time or maybe there was simply an issue when calling the RetroAchievements service to unlock some achievements. There's always something that can go wrong 😛

**Comment by Seaofstars86** [comment]
I feel that it must have been a problem with the page, A few days ago I was crashing often again, I apologize since this was an error on the page and not the emulator, and I really appreciate all the work you have done and I hope the emulator continues getting better
