### ISSUE TITLE
Latest versions immediately crashing upon open

### ISSUE THREAD

**Issue by johnglen559** [rafaelvcaetano/melonDS-android#1239]
* **Device model:** Pixel 6A
* **Android version:** Android 14 UP1A.231105.003

**Problem:**  
Both latest MelonDS beta and nightly are crashing immediately upon open, tried uninstalling and reinstalling, behavior continues

**Comment by johnglen559** [comment]
I had to rollback to 1.8.0 as 1.9.0 is also immediately crashing. Not sure what's going on as 1.9.0 used to function perfectly on my device.

**Comment by johnglen559** [comment]
Latest Google Play version works, seems like only the builds off GitHub are having issues

**Comment by rafaelvcaetano** [comment]
Thanks for reporting this! Turns out this was an issue that was only happening on devices running Android 14 and, as you said, only on GitHub releases. I've pushed the fix. I would appreciate if you could let me know if it's fixed for you :)

**Comment by johnglen559** [comment]
Latest nightly is working wonderfully, no more instant crashes, thank you so much Rafael!
