### ISSUE TITLE
DSi Camera Crash on Xperia 1 V

### ISSUE THREAD

**Issue by Kdash4** [rafaelvcaetano/melonDS-android#1257]
I was happy by reading description of new melonds update that says support dsi camera. However it doesn't work on my device. I can open the dsi camera app on dsi menu and i give permission to melonds for access my camera. I can open the "album" in dsi camera app but when i tap "camera" then melonds crashes. Please fix it. Regards.

Device: Sony Xperia 1 V, Snapdragon 8 gen 2, Adreno 740, Android 13

**Comment by LutraVibes** [comment]
I have the same issue on my Motorola Razr.

**Comment by DolphinOfficial** [comment]
Same issue on Pixel 8 Pro

**Comment by DolphinOfficial** [comment]
Figured it out! It’s because of the wide camera.  For me it only works in landscape orientation. If you try using camera functions in Portrait, it crashes.

**Comment by rafaelvcaetano** [comment]
Finally found a device that can reproduce this crash. But I think it has already been fixed in the [nightly releases](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/nightly-release). Could you guys give it a try?

**Comment by LutraVibes** [comment]
> Finally found a device that can reproduce this crash. But I think it has already been fixed in the [nightly releases](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/nightly-release). Could you guys give it a try?

Yeah, sure. Trying it now

**Comment by LutraVibes** [comment]
Uploading lv_0_20240220105551.mp4…

**Comment by LutraVibes** [comment]
It works! I think it would be nice to be able to switch the camera from front to back, and vice versa in the pause menu and the default camera in video settings.

**Comment by Kdash4** [comment]
Hello, sorry for late reply. Yes that nightly build fixed the camera crash problem. Thanks..
