### ISSUE TITLE
MINIMAL PRIORITY - Failed DSi Boot

### ISSUE THREAD

**Issue by LutraVibes** [rafaelvcaetano/melonDS-android#1258]
* **Device model:** Motorola Razr
* **Android version:** 13
**Problem:**  Failed to boot the DSi firmware.

**Steps to reproduce:**
1. Load custom firmware into MelonDS
2. Launch DSi firmware
3. Error occurs

**Visuals:**

![Screenshot_20231214-185039](https://github.com/rafaelvcaetano/melonDS-android/assets/123699770/75983e3a-4f94-40eb-afcb-94498ca8d988)
![Screenshot_20231214-185045](https://github.com/rafaelvcaetano/melonDS-android/assets/123699770/0acabf30-809e-404a-89b6-44c7eb2b389a)
![Screenshot_20231214-185050](https://github.com/rafaelvcaetano/melonDS-android/assets/123699770/551f5606-e393-484c-8c6d-9b8487b58913)

This is of MINIMAL PRIORITY. Keep up your good work!

**Comment by Kdash4** [comment]
Did you install too many dsi ware title? You exceeded the limit i think. Try deleting games on dsiware manager until you see the error disappear

**Comment by LutraVibes** [comment]
It worked! Thank you so much 🙏
