### ISSUE TITLE
Can't Sign Into Retroachievements

### ISSUE THREAD

**Issue by Namazaki-Kiyo** [rafaelvcaetano/melonDS-android#1261]
* **Device model:** Samsung Galaxy S10e
* **Android version:** 12

**Problem:**  
I downloaded the app from the Playstore a few days ago and the app had been working perfectly. I managed to get signed into my RetroAchievements account and it was playing flawlessly until today.

I managed to play for a few hours, turned off the app when I was finished and when I opened it up again, not only wouldn't the achievement list load, but it wouldn't let me sign in. I keep getting a 'There was a problem when trying to log in'. 

I've tried with and without WiFi, adding custom BIO files, changing the Mac address, tried both the master and nightly builds but it's coming up with the same problem.

**Comment by rafaelvcaetano** [comment]
Thanks for bringing this up. It looks like the guys at RetroAchievements made some changes on their side, which broke the integration with the emulator. I'll look into it.

**Comment by rafaelvcaetano** [comment]
Issue should be now fixed. A new release is being generated. Let me know if everything works fine on your side!

**Comment by Namazaki-Kiyo** [comment]
Perfect, thank you! 🥰 I just updated and checked it. It's working now.
