### ISSUE TITLE
crash import cheatcode

### ISSUE THREAD

**Issue by mikicast01** [rafaelvcaetano/melonDS-android#1264]
phone: Samsung Galaxy A54
android version: 14

Hello, the app I downloaded from play store its work fine, also games.

But when I import cheat code from a YouTube video, it's crashed and I cannot import cheat code.

I have another phone samsung galaxy M52 and android 13, I did test for import cheat code and its worked. How I do?

**Comment by rafaelvcaetano** [comment]
Can you add your XML file here?

**Comment by mikicast01** [comment]
> Can you add your XML file here?

I should add but github doesn't support.

I downloaded from this video youtuber: https://youtu.be/2dcTp7w8a8o?si=isyyne9fglVTQOxs

*Remember that I testes other phone samsung m52 with 13 android is worked fine with cheat code.* I don't think so its flaut the file xml cheat?

**Comment by mikicast01** [comment]
> Can you add your XML file here?

BTW let me know when u know. Merry Christmas!

**Comment by rafaelvcaetano** [comment]
So, Android 14 introduced some changes that broke the cheat import process. Can you try the latest nightly build to see if the issue is fixed for you?

**Comment by mikicast01** [comment]
> So, Android 14 introduced some changes that broke the cheat import process. Can you try the latest nightly build to see if the issue is fixed for you?

ok I'll try

**Comment by mikicast01** [comment]
> So, Android 14 introduced some changes that broke the cheat import process. Can you try the latest nightly build to see if the issue is fixed for you?

it is worked!!! 
Can I may know what are difference melonDS and Melonds nighty?

**Comment by mikicast01** [comment]
tysm!!!

**Comment by rafaelvcaetano** [comment]
The nightly version contains all the latest changes, which may include things that are still being worked on, and may be buggy. The normal version contains stable releases.

**Comment by mikicast01** [comment]
> The nightly version contains all the latest changes, which may include things that are still being worked on, and may be buggy. The normal version contains stable releases.

oh ok top! I hope new update the melods support on samsung android 14 for cheatcode
