### ISSUE TITLE
WFC Connection

### ISSUE THREAD

**Issue by TrueLannak** [rafaelvcaetano/melonDS-android#1269]
Can't connect via any dns server, always got error 52100, searched on the internet for solutions and not found any for android version of melonds.
MelonDS version: 1.9.3 PS

**Comment by rafaelvcaetano** [comment]
Which DNS are you using?

**Comment by TrueLannak** [comment]
Kaeru, Wiimfi, AltWFC, also tried to setup server with RiiConnect.

**Comment by TrueLannak** [comment]
Sorry, accidentally missclicked...

**Comment by TrueLannak** [comment]
Sorry, accidentally missclicked...

**Comment by TrueLannak** [comment]
Solved problem through wfc patcher and russian vpn.
