### ISSUE TITLE
Resize the Screen and Change Position 

### ISSUE THREAD

**Issue by hehk1234** [rafaelvcaetano/melonDS-android#1274]
Good morning Rafael, what's up?

I looked here in all the options and I didn't find the option in the nightly build to resize the DS screens. There are games, like Castlevania, that use the touchscreen and it would be interesting to have the option to optimize its size for better viewing and accessibility. 

Thank you for your commitment and dedication in bringing this excellent project to our little green robot.

**Comment by rafaelvcaetano** [comment]
You can already do this. You need to create a new layout in `Settings > Input > Layouts`. Then, select a screen a drag the slider at the bottom to adjust their size. You can modify the portrait and landscape layouts by rotating your device accordingly.

**Comment by DavidAriyan** [comment]
I hope there's option to change each DS screens to specific ratios eg: 16:9, 16:10...etc to support widescreen cheat. Drastic has this features since it first released. Melonds support manual cheats now, so a custom screen size should make a great addition
