### ISSUE TITLE
I don't know how to exit or change game

### ISSUE THREAD

**Issue by F3nt0n** [rafaelvcaetano/melonDS-android#1277]
I can't find an exit game or change game button anywhere on android? I've seen other issues reference as such but there is no game menu button to add to input. Hoping this is an easy dumb issue I've overlooked.

**Comment by rafaelvcaetano** [comment]
You just need to navigate back on your device. I don't know if you have physical navigation buttons, virtual buttons, or use gesture navigation, but just do what you would normally do to navigate to a previous screen and it will show you the pause menu. You can also create a new layout and add a Pause button for easier access.

**Comment by F3nt0n** [comment]
Thanks so much! Both suggestions to my dumb question worked thank you.

**Comment by F3nt0n** [comment]
Thanks so much! Both suggestions to my dumb question worked thank you.
