### ISSUE TITLE
App doesn't load existing saves

### ISSUE THREAD

**Issue by Z11xe** [rafaelvcaetano/melonDS-android#1291]
* **Device model:** Vivo X80 Lite 5G (CPU is Dimensity 900)
* **Android version:** 13

**Problem:**  
Already existing save files do not load, all games I tried just show new game 

**Steps to reproduce (if applicable):**
1. Copy existing saves to save file directory 
2. Set that directory in the settings (can be both with roms or separate)
3. Load a game, the game shows new game and can't load the existing save (even if it's named same as the rom

Add screenshots if the issue can be visualized:

![Screenshot_20240309_150248_me.magnum.melonds.jpg](https://github.com/rafaelvcaetano/melonDS-android/assets/155079832/79e4484d-227c-4afc-9b41-cd930c7ace09)

![Screenshot_20240309_150224_me.magnum.melonds.jpg](https://github.com/rafaelvcaetano/melonDS-android/assets/155079832/684bece6-45b6-43d1-b688-5d258e366d45)

**Comment by WinUser-Generic** [comment]
Try reseting your bios files, i mean, install again or find new ones.

**Comment by Z11xe** [comment]
> Try reseting your bios files, i mean, install again or find new ones. also can help clear cache and data of app before reinstall bios, you only can lose app settings but are easy and fast to resetup.

Weird, I'll try but I used the default included bios on both of my phones, I'll look though

**Comment by rafaelvcaetano** [comment]
Sorry for the late reply. Could you show me some screenshots of the folder in which you have your ROMs and the one in which you have your save files?

**Comment by Z11xe** [comment]
> Sorry for the late reply. Could you show me some screenshots of the folder in which you have your ROMs and the one in which you have your save files? 

Yup here it is, if you need more info let me know

![Screenshot_20240314_161912.jpg](https://github.com/rafaelvcaetano/melonDS-android/assets/155079832/8835fa4e-3421-4b1a-873d-25c76816ce60)

![Screenshot_20240314_161933.jpg](https://github.com/rafaelvcaetano/melonDS-android/assets/155079832/efc57d10-edb7-4bec-9bec-9207c490fea4)

(Also one little note, no achievements seem to load for Platinum even though it's retroachievements page shows that it has achievements, but I probably should open a new issue for this)

![Screenshot_20240314_162418_me.magnum.melonds.jpg](https://github.com/rafaelvcaetano/melonDS-android/assets/155079832/7c129f63-be85-46e9-9607-78f4e8801fa8)

**Comment by Z11xe** [comment]
One little note, the reason that the folder is named Nokia is because it was my old phone so I just named it after it, idk why to be honest

**Comment by WinUser-Generic** [comment]
The only differences with me i can see:
1. you have roms zipped, in my case are in .ds 
2. the saves are in .bin, mine are in .sav

I dont know if something of this can be the trouble.

**Comment by Z11xe** [comment]
> saves are in .bin

Well they are .sav (or at least I think), android just doesn't show unknown file extensions (and I don't know how to turn it off), so if you download an exe it also shows as .bin

**Comment by rafaelvcaetano** [comment]
Actually, your save files have no extension. You need to manually add the `.sav` extension to each of your files. Look how the ZIP files show the `.zip` extension in the name.

**Comment by Z11xe** [comment]
> Actually, your save files have no extension. You need to manually add the `.sav` extension to each of your files. Look how the ZIP files show the `.zip` extension in the name.

Okay so I just tried that, I always thought it was just android doing some stupid stuff like windows does (they also hide file extensions by default) but it was the cause of the problem, sorry for wasting your time
