### ISSUE TITLE
Cheat Not Working

### ISSUE THREAD

**Issue by reevine** [rafaelvcaetano/melonDS-android#1305]
**Device model:** Samsung Galaxy S24
**Android version:** 14

**Problem:**
Cheats function does not work on Play Store version of the app or the Nightly build. When trying to add cheats in the app it fails to load any .xml file. App either crashes, goes back to ROM list, or shows a frozen progress bar and does not load any data. I've tested this with multiple .xml files of different sizes and on three different Android devices running Android versions 12, 13, and 14.

**Steps to reproduce (if applicable):**
1. Launch ROM
2. Go to Settings > Cheats
3. Import cheats file > select .xml
4. Import fails and crashes app

**Comment by rafaelvcaetano** [comment]
This is a known issue which has already been fixed but the fix has not been pushed to the Play Store release yet. If you don't want to wait, you can try using the Nightly release, which you can find [here](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/nightly-release).
