### ISSUE TITLE
Retroachievements stops working

### ISSUE THREAD

**Issue by Rated223** [rafaelvcaetano/melonDS-android#1316]
* **Device model:** Ayn Odin 2
* **Android version:** 13

**Problem:**  
After playing for some time the achievements stop registering. When you restart the application it works again.

**Possible causes:**
1. Use the reset option from emulator menu
2. Enter to see achievements from emulator menu
3. Use the emulator for a long period of time (3-4 hours)

**Comment by Rated223** [comment]
Testing it further I found the reset option as the cause of the problem, I share a video with an achievement upon reaching level 50. (sorry for the length, it was the achievement I had at hand)

[video](https://drive.google.com/file/d/1edpnPGOffIhEqm5d7c5MzM1GSVyZEUvO/view?usp=sharing)

**Comment by rafaelvcaetano** [comment]
Thanks for the in-depth testing! I have pushed a fix that will be available in a couple of minutes in the Nightly Release. Let me know if it fixes your problem!

**Comment by Rated223** [comment]
Hey, it works now, thanks!

[video](https://drive.google.com/file/d/1J9hoxA1siMYp7enbf40f5mG0lfBPvmT4/view?usp=sharing)
