### ISSUE TITLE
Unable to boot to DSi mode 

### ISSUE THREAD

**Issue by soulpower11** [rafaelvcaetano/melonDS-android#133]
* **Device model:** SM-G965F
* **Android version:** Android API 29
* **melonDS version:** Beta 1.2.2

**Problem:**  
Booting into DSi mode causes the error, even though I have all the bios file needed in the folder and also tested them out on the pc version

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$d: Failed to load firmware: BIOS9_MISSING
	at me.magnum.melonds.ui.emulator.h$c.a(Unknown Source:54)
	at f.a.b0.e.a.a.g(Unknown Source:10)
	at f.a.a.a(Unknown Source:14)
	at f.a.b0.e.a.e$a.run(Unknown Source:2)
	at f.a.r$a.run(Unknown Source:9)
	at f.a.b0.g.j.run(Unknown Source:13)
	at f.a.b0.g.j.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Configuration:**  
```
FirmwareCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, dsConfigDirectory=null/, dsiConfigDirectory=/storage/8605-9295/MelonDS/DSi NAND and firmware/, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=true, consoleType=DSi, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)))
```

**Comment by rafaelvcaetano** [comment]
DSi requires the BIOS files from both the DS and DSi. I know the UX is terrible regarding this point but I'm thinking about how to do it better.  
So, set the path to your DS BIOS directory and try again. It should work.

**Comment by soulpower11** [comment]
Okay, I managed to get it to boot, but now I am getting Error: 1-2435-8325 with the bios files I am using, which is some HiyaCFW error

**Comment by rafaelvcaetano** [comment]
At which point does the error appear?

Regarding file names, if there is a warning indicator in the option to select the directory, you can click that icon to see what's missing. If there's no icon, everything is OK.

**Comment by soulpower11** [comment]
The error appears when I use the boot into DSi Mode using the boot firmware option or when I set the default system to a DSi and boot a game.

![explorer_2021-03-01_09-37-35](https://user-images.githubusercontent.com/5299979/109442033-fb3e7680-7a71-11eb-9ead-3352b91cd786.png)
![Screenshot_20210301-093759_melonDS](https://user-images.githubusercontent.com/5299979/109442037-fbd70d00-7a71-11eb-9c27-ef5efd4ce153.jpg)

**Comment by rafaelvcaetano** [comment]
The DS and DSi files can't be in the same directory because the file names are the same.

**Comment by soulpower11** [comment]
I separated it to their own directory and it is still the same, still shows Error: 1-2435-8325 when I boot into DSi mode, works fine when it's DS mode

**Comment by rafaelvcaetano** [comment]
I recommend you to delete and extract all BIOS files again because you might have mixed them while they were all in the same directory.

**Comment by soulpower11** [comment]
Okay, I did that and it is still the same

**Comment by rafaelvcaetano** [comment]
Can you give me a screenshot of your custom BIOS settings screen?

**Comment by soulpower11** [comment]
![Uploading Screenshot_20210301-095919_melonDS.jpg…]()

**Comment by soulpower11** [comment]
![Screenshot_20210301-095919_melonDS](https://user-images.githubusercontent.com/5299979/109443253-0ba42080-7a75-11eb-83e6-79889878ab79.jpg)

**Comment by rafaelvcaetano** [comment]
According to this (https://dsibrew.org/wiki/Bootloader), it looks like there's something wrong with the NAND (or the way it's loaded). It's late over here so I'll keep investigating tomorrow.

**Comment by soulpower11** [comment]
Okay, I will try dumping the NAND on my own DSi and see if it fixes it

**Comment by soulpower11** [comment]
Okay so I messed around with some phones that I have, when I tried it on my LG G5 running Android 8 and Galaxy S9+ running Android 10, Error: 1-2435-8325 is shown when I boot into DSi Mode. When I tried it with my Galaxy S20 Ultra running Android 11 and Mi 9 running Android 10, it was able to boot into DSi Mode without any issue. 

I found an issue that was closed of someone else running a Samsung phone that when got updated to Android 11, the Error code went away (https://github.com/rafaelvcaetano/melonDS-android/issues/55)

So it might be something to do with Samsung's OneUI? I don't really know anything about how android works so I am not sure what could be the issue. But I hope this helps you

**Comment by rafaelvcaetano** [comment]
That's some seriously valuable insight. Working with Android regarding file handling has been a terrible experience since they started forcing the use of their "Scoped Storage". The fact different devices have different implementations just makes things more difficult. So, at least, this helps narrow the problem down. Thanks!

**Comment by soulpower11** [comment]
You're welcome.

btw just like in issue #55, when I move my bios files to the internal storage of my Galaxy S9+, it started to boot into DSi Mode without any issue soo it's probably some permission issue?

**Comment by rafaelvcaetano** [comment]
It shouldn't be related to permissions but rather how files are being handled in the emulation side, which is completely different from how they are handled in the frontend side. And the conversion must be behaving incorrectly in some scenarios, specially if the files are in the external storage.

**Comment by dreamboyn81** [comment]
> 它不应该与权限相关，而应该与在仿真端处理文件的方式有关，这与在前端处理文件的方式完全不同。并且在某些情况下，转换的行为必须不正确，特别是如果文件在外部存储中。

It may be that DSI games are installed too much, this error will also occur, or the startup will have a blank screen.
I tried to add games according to the tutorial and tried many times.
Obviously there are 32+ game slots, but only about 7 big games or 16 small games can be installed.
I don’t know why, and can NAND files exceed 240MB?

**Comment by rafaelvcaetano** [comment]
I have no idea. I've never had a DSi system 😔

**Comment by soulpower11** [comment]
I don't think it is a problem with the NAND? If it is it shouldn't be able to even boot up on the pc or when I use the internal storage

**Comment by Computerdude77** [comment]
OP of #55 here, I'm a little late but I might as well give some insight into this and some more detailed specs, as I was not very clear in the other post. I can see that a theory proposed in the thread is that it could be something to do with OneUI, so I will list my versions to try and narrow that issue down if that is indeed the case. At the time of me opening that issue, my OneUI version was 2.1 (which appears to be the same version soulpower11 has from looking up the phone model number), and once it got the Android 11 update which fixed that bug, it has been updated to 3.0, so I suspect that if OneUI is the problem and not Android itself, it must have been fixed between those 2 versions. It sounds like that the file system of Android is weird to work with, so it could be something completely unrelated, but hopefully this helps a little bit. Keep up the good work!

**Comment by shabbirmahmud** [comment]
Duplicate of #44

**Comment by soulpower11** [comment]
This is solved with the latest update
