### ISSUE TITLE
melonDS-android crashes whenever I attempt to import cheats

### ISSUE THREAD

**Issue by barribad** [rafaelvcaetano/melonDS-android#1367]
* **Device model:** Galaxy S24
* **Android version:** Android 15 - One Ui 7 Beta

**Problem:**  
Pretty much as the title says: whenever I try to select an XML file to import cheats, the app crashes completely. After reopening the app and trying again, it gets stuck at 'starting to import' and loads endlessly.

**Steps to reproduce (if applicable):**
1. Open the cheats settings
2. Select the XML file
3. The app crashes completely
4. Reopen melonDS
5. Try selecting the XML file again
6. The "Importing cheats" pop-up appears but loads indefinitely

    https://github.com/user-attachments/assets/c770a8ff-eae5-4325-8a47-3ae6d5a05192

**Comment by barribad** [comment]
Just tested the nightly version and it works without any issues

**Comment by barribad** [comment]
Duplicate of https://github.com/rafaelvcaetano/melonDS-android/issues/1305

**Comment by mrTerryBogard** [comment]
Android 14
Latest stable 1.9.3. It doesn't matter where from. Crash when choosing cheats.
