### ISSUE TITLE
Lag

### ISSUE THREAD

**Issue by ASGAMING009** [rafaelvcaetano/melonDS-android#142]
Can you fix lag please or atleast get 30fps please @rafaelvcaetano

**Comment by ASGAMING009** [comment]
In Know Your A Busy Guy But Please

**Comment by shabbirmahmud** [comment]
Yep compared to the drastic ds emulator melonds is very laggy.It needs more optimization.

Watch in this video-https://youtu.be/bmqV7P0dg-c

**Comment by shabbirmahmud** [comment]
Duplicate of #231

**Comment by rafaelvcaetano** [comment]
Sorry for not giving this issue any attention. There's nothing I can regarding performance right now but naturally, the performance should improve with time. So, keep trying the latest versions.
