### ISSUE TITLE
Request: will come on playstore?

### ISSUE THREAD

**Issue by lucariokalos** [rafaelvcaetano/melonDS-android#15]
I want to see in playstore.

**Comment by rafaelvcaetano** [comment]
Most likely. I still want to improve it a bit more though. The current performance level would leave a lot of users disappointed.

**Comment by lucariokalos** [comment]
On future update will increase the speed?

**Comment by rafaelvcaetano** [comment]
Eventually, yes.

**Comment by lucariokalos** [comment]
First of all,need improve the speed then release on playstore.

**Comment by shabbirmahmud** [comment]
Duplicate of #33

**Comment by rafaelvcaetano** [comment]
melonDS is now available on the Play Store.
