### ISSUE TITLE
Question: is melon ds emulator have full screen mode like my boy emulator

### ISSUE THREAD

**Issue by lucariokalos** [rafaelvcaetano/melonDS-android#16]

**Comment by rafaelvcaetano** [comment]
Do you mean like, stretching the image to fill the screen?

**Comment by HJMBgit84** [comment]
Maybe he is asking for landscape mode I think

**Comment by lucariokalos** [comment]
I mean fill the screen

**Comment by lucariokalos** [comment]
In my phone the melon Ds is full screen.

**Comment by rafaelvcaetano** [comment]
I'm not sure if this is what you expected, but since the latest version you can now resize the screen however you like. I will close this issue but feel free to open a new one if you had something else in mind.
