### ISSUE TITLE
Question: Bios

### ISSUE THREAD

**Issue by Fietoo** [rafaelvcaetano/melonDS-android#17]
Will you ever add DSi mode like the pc version? (Running DSi bios and nand)

**Comment by rafaelvcaetano** [comment]
Probably, yes. As soon as the next PC version is released, I plan to take a look at it.

**Comment by D-pixel203** [comment]
Where can i get the BIOS for android?

**Comment by rafaelvcaetano** [comment]
> Where can i get the BIOS for android?

You need to dump it yourself from a real NDS. I won't go into details but you can search for tutorials. Alternatively, you might find dumps online but that's illegal so lets not discuss that here.

**Comment by ariebe9115** [comment]
Oh please add the DSi Mode, i would love to make NAND Projects on my Mobile Phone

**Comment by rafaelvcaetano** [comment]
DSi support is now available on release Beta 1.0.0
