### ISSUE TITLE
Showing white screen without custom bios

### ISSUE THREAD

**Issue by shabbirmahmud** [rafaelvcaetano/melonDS-android#172]
Device-Redmi 5+,Realme 5i
MelonDs Version- beta v1.2.2
No rom load either it is in internal storage or external, inside the internal download folder or outside the download folder.Only show a white screen.

https://user-images.githubusercontent.com/47573399/110953314-6725b680-8371-11eb-82ff-2acfc4a36a81.mp4

**Comment by rafaelvcaetano** [comment]
Can you try other ROMs?

**Comment by shabbirmahmud** [comment]
> Can you try other ROMs?

I tried all my favourite pokemon games bt all are same.

https://user-images.githubusercontent.com/47573399/110954419-ad2f4a00-8372-11eb-87fe-16ae2121a280.mp4

**Comment by rafaelvcaetano** [comment]
Do they work if you extract them?

**Comment by shabbirmahmud** [comment]
> Do they work if you extract them?

No it's same after extract the rom in any directories.

**Comment by shabbirmahmud** [comment]
But the rom load when custom bios is turned on in any directories (Inside the download folder too)

**Comment by shabbirmahmud** [comment]
Still don't open rom inside the download folder when custom bios is turned off on beta v1.3.0.

**Comment by shabbirmahmud** [comment]
Duplicate of #79

**Comment by rafaelvcaetano** [comment]
Try the latest [Beta 1.4.0](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) release. There were some problems when loading ROMs under certain emulator configurations. Let me know if it's fixed.

**Comment by shabbirmahmud** [comment]
> Try the latest [Beta 1.4.0](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) release. There were some problems when loading ROMs under certain emulator configurations. Let me know if it's fixed.

Yep it fixes now🤠😊.The roms are loading without the custom bios(Zip Unzip Both).No white screen anymore.Thank u very much.Keep up the good work😊🥰.
You can close this issu now.

**Comment by TomSalvador90** [comment]
I suspect there's a regression in this issue, as I'm experiencing exactly the same problem with the new 1.10.0 Beta.

**Comment by HybridShivam** [comment]
MelonDS 1.10.0
Same issue
I tried Pokemon Black 2
