### ISSUE TITLE
DSI Bios download

### ISSUE THREAD

**Issue by Tonystarsyt** [rafaelvcaetano/melonDS-android#179]
Please pass the bios of the dsi

**Comment by rafaelvcaetano** [comment]
Sorry, but you will have to dump it from a real system or find it somewhere else. I can't give you links since that's illegal.

**Comment by Tonystarsyt** [comment]
> Sorry, but you will have to dump it from a real system or find it somewhere else. I can't give you links since that's illegal.

Ok :(
