### ISSUE TITLE
Display problem

### ISSUE THREAD

**Issue by butterfly2706** [rafaelvcaetano/melonDS-android#181]
Latest update does this when doing a split screen (and opening another 'instance' via cloning apps)

![160317046_2841068612816722_4897568034686405156_n](https://user-images.githubusercontent.com/80578498/111058143-5f782600-84c7-11eb-8e71-5022da650b00.jpg)

for comparison, this is what it looks like in 1.2.2 version
![160568801_286754386129995_5285018246775806175_n](https://user-images.githubusercontent.com/80578498/111058169-833b6c00-84c7-11eb-9524-96178ddd36bd.jpg)

I think the ability to customize the layout clashes with the display being constrained.
Using the default layout doesn't help either

**Comment by shabbirmahmud** [comment]
Just make a custom layout for split screen like this-
![Screenshot_2021-03-14-11-25-39-19_e7877f9796c3bfb5a5339f6b3513bed1](https://user-images.githubusercontent.com/47573399/111058330-17053c00-84b8-11eb-9497-4403c911f31b.jpg)

**Comment by butterfly2706** [comment]
@shabbirmahmud is it possible to resize the buttons, etc?

**Comment by shabbirmahmud** [comment]
> @shabbirmahmud is it possible to resize the buttons, etc?

Yep you can.

**Comment by butterfly2706** [comment]
I see, that's 1 thing I missed. thanks

**Comment by butterfly2706** [comment]
I can't seem to make
