### ISSUE TITLE
Haptic feedback intensity slider

### ISSUE THREAD

**Issue by ghost** [rafaelvcaetano/melonDS-android#184]
* **Device model:** OnePlus 7T Pro
* **Android version:** 10

**Problem:**  
Haptic feedback for me personally is a bit weak, would be good to have a slider so you can adjust the intensity of how strong/weak you want the haptic feedback when using the touch screen controls.

**Steps to reproduce (if applicable):**
1. Enable haptic feedback
2. Touch the on screen controls
3. Vibrates but not as strong as I want it to be

**Comment by rafaelvcaetano** [comment]
This feature has been introduced in the [Beta 1.6.0](https://github.com/rafaelvcaetano/melonDS-android/releases) release. If you have further suggestions for this feature, let me know.
