### ISSUE TITLE
What is the left center button with two arrows?

### ISSUE THREAD

**Issue by HJMBgit84** [rafaelvcaetano/melonDS-android#19]
When I touched the button placed in the center next to the make available screen buttons my screen only goes in blank so I have no idea what is the function of this button that has icon of an arrow with opposite directions. Could you explain please?

**Comment by rafaelvcaetano** [comment]
It's to simulate you physically closing/opening the console. Some games use that feature as a gameplay mechanic.

Here is an example of a game that uses this mechanic (**WARNING**: may contain Legend of Zelda Phantom Hourglass spoilers): https://www.youtube.com/watch?v=1u3uq2CBgj4

**Comment by HJMBgit84** [comment]
Oh is like pause the game as I see, is like an stand by mode right?

**Comment by rafaelvcaetano** [comment]
Exactly. But there's no benefit to using it in the emulator other than in games that use it as a mechanic.

**Comment by HJMBgit84** [comment]
Ok ok thanks for clarifying :)
