### ISSUE TITLE
File selection won't work on Google Pixel phone

### ISSUE THREAD

**Issue by turboboy215** [rafaelvcaetano/melonDS-android#2]
I downloaded the latest alpha APK, but when I try to locate the BIOS or select a ROM, it opens up a file selection menu that says "SD card" at the top and I can't select or see anything, only cancel, which is likely because my phone, which is a Google Pixel 3, doesn't have an SD card, and it defaults to that. Can this be fixed?

**Comment by mn26** [comment]
Looks like we submitted at the same time. I found a fix for this, see [my issue](https://github.com/rafaelvcaetano/melonDS-android/issues/3).

**Comment by mn26** [comment]
Also sdcard is a directory that actually refers to the internal file system. It's confusing.

**Comment by rafaelvcaetano** [comment]
A hotfix has been released under version [Alpha 1.2.1](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/alpha-1.2.1). I tested it on my Galaxy S10 running Android 10 and found no problems. But I never had problems with it in the first place, so ¯\\_(ツ)_/¯.

Please try the new version and let me know if the issue has been fixed :)

**Comment by hohommx2015** [comment]
It's fixed,thanks

**Comment by Someguy1519** [comment]
> A hotfix has been released under version [Alpha 1.2.1](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/alpha-1.2.1). I tested it on my Galaxy S10 running Android 10 and found no problems. But I never had problems with it in the first place, so ¯\_(ツ)_/¯.
> 
> Please try the new version and let me know if the issue has been fixed :)

I still can't select my BIOS on my Galaxy S8+ running Android 9 with version 1.2.1

**Comment by rafaelvcaetano** [comment]
> I still can't select my BIOS on my Galaxy S8+ running Android 9 with version 1.2.1

I just tested this on a Galaxy S8 running Android 9 and had no problem selecting the BIOS directory. What is exactly happening? When you click on the "BIOS directory" button does anything appear? Can you see the popup dialog? Is any directory shown?

**Comment by Someguy1519** [comment]
> > I still can't select my BIOS on my Galaxy S8+ running Android 9 with version 1.2.1
> 
> I just tested this on a Galaxy S8 running Android 9 and had no problem selecting the BIOS directory. What is exactly happening? When you click on the "BIOS directory" button does anything appear? Can you see the popup dialog? Is any directory shown?

When I go to the directory where my BIOS files are the select button is greyed out.

**Comment by rafaelvcaetano** [comment]
> When I go to the directory where my BIOS files are the select button is greyed out.

That seems to be a UX problem. You don't need to go inside the BIOS directory. Go the the parent of that directory and select the checkbox of your actual BIOS directory. Then, the SELECT button will be enabled.
