### ISSUE TITLE
El emulador no quiere dejarme entrar a los juegos y cuando trato de hacer otros intentos con los bios y los roms falla!!

### ISSUE THREAD

**Issue by sailsaro23** [rafaelvcaetano/melonDS-android#214]
* **Device model:** 5059S
* **Android version:** Android API 27
* **melonDS version:** Beta 1.2.2

**Problem:**  
Insert a small description of the problem.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$f: Failed to load ROM: NDS_FAILED
	at me.magnum.melonds.ui.emulator.j$e$a$a.a(Unknown Source:204)
	at f.a.b0.e.e.a.o(Unknown Source:10)
	at f.a.s.a(Unknown Source:14)
	at f.a.b0.e.b.e$a.d(Unknown Source:26)
	at f.a.b0.e.b.l$a.d(Unknown Source:2)
	at f.a.b0.e.b.j$a.run(Unknown Source:21)
	at f.a.r$a.run(Unknown Source:9)
	at f.a.b0.g.j.run(Unknown Source:13)
	at f.a.b0.g.j.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, dsConfigDirectory=//, dsiConfigDirectory=//, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=false, consoleType=DS, soundEnabled=true, micSource=DEVICE, firmwareConfiguration=FirmwareConfiguration(nickname=sailsaro23, message=hola!, language=5, favouriteColour=10, birthdayMonth=6, birthdayDay=2), rendererConfiguration=RendererConfiguration(videoFiltering=NONE, threadedRendering=true)), romPath=/storage/raw//storage/emulated/0/Download/DS roms/0022 - Super Mario 64 DS (E)(Wet 'N' Wild).nds, sramPath=/storage/raw/storage/emulated/0/Download/DS roms/0022 - Super Mario 64 DS (E)(Wet 'N' Wild).sav)
```

**Comment by rafaelvcaetano** [comment]
Usa la última versión [Beta 1.3.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.3.0) en donde ese problema fué corregido. Tendrás que desactivar la opción "Custom BIOS and firmware".

**Comment by sailsaro23** [comment]
Lo he intentado con la nueva versión y no he podido entrar a ningún rom
y me decía algo de firmware pero ahí no se que hacer ... Me puede dar algún
consejo sobre eso?

**Comment by rafaelvcaetano** [comment]
Has desactivado la opción "Custom BIOS and firmware" en las configuraciones?

**Comment by sailsaro23** [comment]
Si lo hice y nada

**Comment by rafaelvcaetano** [comment]
Que mismo te sale? Te dice para abrir un nuevo issue en GitHub?

**Comment by sailsaro23** [comment]
Si, siempre que cambio alguna configuración, no importa cuál me sigue
apareciendo

**Comment by rafaelvcaetano** [comment]
Pon los ficheros ROM en una carpeta afuera de Download y actualiza el camino en las configuraciones.

**Comment by sailsaro23** [comment]
Hise lo que me dijiste y cuando pongo el rom se pone en pantalla blanca

**Comment by shabbirmahmud** [comment]
> Hise lo que me dijiste y cuando pongo el rom se pone en pantalla blanca

Put the rom and bios outside the download folder.
If turning off custom firmware show white screen(Some phone shows white screen #172) then turn on custom Firmware again.It should solve the problem.

**Comment by sailsaro23** [comment]
Thank you very much, the game started to run ... but another thing, can you
give me advice to lower the lag of the emulator because when I put the
emulator and the rom it makes me very laggy

**Comment by shabbirmahmud** [comment]
> Thank you very much, the game started to run ... but another thing, can you give me advice to lower the lag of the emulator because when I put the emulator and the rom it makes me very laggy 

Unfortunately there is no workaround to lower the lag.The emu needs more optimization for low end  and mid range processors.Highly you can turn on fast-forward mode.Stop background apps and if you have performance mode or gaming mode you can turn on or use custom rom.This will slightly increase gaming performance and reduce lag.

**Comment by sailsaro23** [comment]
Ok thanks
