### ISSUE TITLE
Crash when attempting to go online

### ISSUE THREAD

**Issue by GrayGames** [rafaelvcaetano/melonDS-android#23]
I've attempted this with a chromebook with android capabilities and my Galaxy s8, both crash when attempting to connect to the internet in Mario Kart DS. It should be possible on the Chromebook and even an android device with an external wifi card + Wifi PCAP Capture on the Play Store. Please fix this crash so I can do further wifi testing... a menu to select the connections-- similar to the full version of melonds would be nice as well.

**Comment by rafaelvcaetano** [comment]
Wi-Fi is not yet supported and probably won't be as long as PCAP is required. For the next PC version, it should be dropped in favor of libslirp, which should make things much easier to port. Until then, nothing Wi-Fi related will work. And even then, I can't make promises.
