### ISSUE TITLE
Games doesn't show

### ISSUE THREAD

**Issue by alwaysdimdim** [rafaelvcaetano/melonDS-android#233]
Why the games doesn't show in the boot screen
![Screenshot_2021-03-22-12-51-00-73](https://user-images.githubusercontent.com/79393179/111946324-d8056500-8b0d-11eb-9a96-92c7eecf95be.jpg)
![Screenshot_2021-03-22-12-50-30-96](https://user-images.githubusercontent.com/79393179/111946336-dd62af80-8b0d-11eb-95e1-d22552696808.jpg)

**Comment by rafaelvcaetano** [comment]
Have you set the DS BIOS directory? I know it's not explicit, but the DSi also requires the DS BIOS files.

**Comment by alwaysdimdim** [comment]
![Screenshot_2021-03-22-23-31-39-38](https://user-images.githubusercontent.com/79393179/112024772-1a0ec500-8b67-11eb-8985-68d3235875bf.jpg)
yeah, I already set all the bios but it's still like this

**Comment by alwaysdimdim** [comment]
Pokemon,Digimon,ninokuni,Mario.I've tried it, I haven't found a solution

**Comment by shabbirmahmud** [comment]
Turn off the show boot screen and check if it loads the rom.If it doesn't then use ds firmware and check if it's detect the rom.

And lastly is your rom is in zip formate?If yes then extract it and check is it can detect the rom or not?

**Comment by alwaysdimdim** [comment]
https://user-images.githubusercontent.com/79393179/112079706-3afd0780-8bb3-11eb-9c29-817439411e58.mp4

I tried it but this is what happened

my rom is nds not zip format

**Comment by alwaysdimdim** [comment]
![Uploading Screenshot_2021-03-23-13-19-03-14.jpg…]()

**Comment by shabbirmahmud** [comment]
> I tried it but this is what happend

What is ur default boot system? Make it ds and check again.
![Screenshot_2021-03-23-16-33-56-87](https://user-images.githubusercontent.com/47573399/112133269-ba132f80-8bf5-11eb-9212-943fdb069594.jpg)

**Comment by alwaysdimdim** [comment]
I've tried it yet nothing changes

**Comment by shabbirmahmud** [comment]
> I've tried it yet nothing changes

Clear the data of the emulator and move your bios and roms somewhere and try again.

**Comment by rafaelvcaetano** [comment]
The problem seems to be in the path of the ROMs. Could you show me the directory in which you placed your ROMs? Not from the emulator settings (because that's visible in your screen recording), but in your file explorer.

**Comment by shabbirmahmud** [comment]
Maybe his problem is like this-

https://user-images.githubusercontent.com/47573399/112189913-b2bc4800-8c2e-11eb-9ea4-45b81bdad329.mp4

**Comment by alwaysdimdim** [comment]
> Maybe his problem is like this-
> 
>  Record_2021-03-23-23-21-16_db51e592e420a9871f4a37915a68789b.mp4

Nah,the problem is the same as that

**Comment by alwaysdimdim** [comment]
> The problem seems to be in the path of the ROMs. Could you show me the directory in which you placed your ROMs? Not from the emulator settings (because that's visible in your screen recording), but in your file explorer.

![Screenshot_2021-03-24-00-51-42-83](https://user-images.githubusercontent.com/79393179/112194733-c4f0b300-8c3b-11eb-9cc3-d84e3cece18d.jpg)

**Comment by shabbirmahmud** [comment]
> Nah,the problem is the same as that

Did you extracted the rom from zip formate like me?

**Comment by shabbirmahmud** [comment]
Is your #79 problem solved?

**Comment by alwaysdimdim** [comment]
> Was your #79 problem solved?

No, because at that time I was busy, so I haven't tried again.

**Comment by alwaysdimdim** [comment]
> > Nah,the problem is the same as that
> 
> Did you extracted the rom from zip formate like me?

I extracted it from 7z

**Comment by shabbirmahmud** [comment]
> No, because at that time I was busy, so I haven't tried again.

Is white screen problem still happen?Did it happen when custom bios is turned off?Which melonds version u was using?And what version u are using now?

**Comment by shabbirmahmud** [comment]
> I extracted it from 7z

After extraction you deleted the 7z file?If yes then was it in the same directory where the nds rom is?If yes then ig your problem is similar to mine(video above).But for me the problem automatically solve after 2 or 3 hours.Then i can open the rom again.Idk how?You can try to move your rom some other directories.

**Comment by alwaysdimdim** [comment]
Yes, the white screen still happens when I turn off the custom BIOS. When I use beta 1.3.0, I just moved the extract of the file to another folder in the internal storage. I was still confused even though I also had followed several ways in response to other issues

**Comment by alwaysdimdim** [comment]
Does fps quality affect this problem? when I turn it on the boot screen gets 50-67 fps, but when I turn it off the boot screen only gets 10-38 fps.

**Comment by shabbirmahmud** [comment]
>When I use beta 1.3.0, I just moved the extract of the file to another folder in the internal storage.

Is the rom being detected now?

**Comment by shabbirmahmud** [comment]
> Does fps quality affect this problem? when I turn it on the boot screen gets 50-67 fps, but when I turn it off the boot screen only gets 10-38 fps.

If you turn on boot screen it will first load the firmware file boot screen.If you turn it off it will directly load the rom.The fps can be vary between firmware and rom ig.

**Comment by rafaelvcaetano** [comment]
Try the latest [Beta 1.4.0](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) release. There were some problems loading ROMs under certain emulator configurations. Let me know if it's fixed.

**Comment by alwaysdimdim** [comment]
I tested right now and finally i can play this emulator thank you
