### ISSUE TITLE
could not load rom

### ISSUE THREAD

**Issue by karlsefinn** [rafaelvcaetano/melonDS-android#255]
* **Device model:** SM-A307GT
* **Android version:** Android API 29
* **melonDS version:** Beta 1.3.0

**Problem:**  
the rom isnt loading and i've already verified multiple times and it is perfectly fine 

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$f: Failed to load ROM: NDS_FAILED
	at me.magnum.melonds.ui.emulator.j$e$a$a.a(Unknown Source:204)
	at f.a.b0.e.e.a.q(Unknown Source:10)
	at f.a.s.a(Unknown Source:14)
	at f.a.b0.e.b.e$a.d(Unknown Source:26)
	at f.a.b0.e.b.l$a.d(Unknown Source:2)
	at f.a.b0.e.b.j$a.run(Unknown Source:21)
	at f.a.r$a.run(Unknown Source:9)
	at f.a.b0.g.k.run(Unknown Source:13)
	at f.a.b0.g.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Configuration:**  
```
RomCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=false, dsConfigDirectory=null/, dsiConfigDirectory=null/, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=true, consoleType=DS, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), romSearchDirUri=content://com.android.providers.downloads.documents/tree/downloads, romUri=content://com.android.providers.downloads.documents/tree/downloads/document/msf%3A21638, romPath=/storage/msf/21638, sramPath=/storage/msf/21638.sav)
```

**Comment by strikersix23** [comment]
So when chosing rom path did you a system file manager
I have the same when using using android 10 
This path is an issue that I don't know why anything even exists

romSearchDirUri=content://com.android.providers.downloads.documents/tree/downloads
anything that has the android path that starts with this com.android.providers.downloads.documents there are other issues related to this.
Id recommend using material files as a selecter

@rafaelvcaetano. Is it possible to re-`nable the sekection dialog from 1.1 alpha as another app called limbo emulator has a similar issue but I fixed by using the legacy file picker

**Comment by karlsefinn** [comment]
you helped me a lot, thanks! ive sorted the rest by myself and discoreved that exists a setting which allows bios and firmware's customizations, so i just turned on the option and changed the ds bios directory, and now i can choose any folder without problems! and really, it is so easy, its a relief
i just needed the .bin files, and i found them on this [http://www.emuparadise.me/biosfiles/NDSBiosFirmware.rar](link)

then you gonna change the names (they are like biosnds7.rom etc) to bios7.bin and bios9.bin and place them inside the selected folder on the bios and firmwares customizations option!

**Comment by karlsefinn** [comment]
> So when chosing rom path did you a system file manager
> I have the same issue when using using android 10 
> This path is an issue that I don't know why anything even exists
> 
> romSearchDirUri=content://com.android.providers.downloads.documents/tree/downloads
> anything that has the android path that starts with this com.android.providers.downloads.documents there are other issues related to this.
> Id recommend using material files as a selecter
> 
> @rafaelvcaetano. Is it possible to re-`nable the sekection dialog from 1.1 alpha as another app called limbo emulator has a similar issue but I fixed by using the legacy file picker

you helped me a lot, thanks! ive sorted the rest by myself and discoreved that exists a setting which allows bios and firmware's customizations, so i just turned on the option and changed the ds bios directory, and now i can choose any folder without problems! and really, it is so easy, its a relief
i just needed the .bin files, and i found them on this link here: http://www.emuparadise.me/biosfiles/NDSBiosFirmware.rar

then you gonna change the names (they are like biosnds7.rom etc) to bios7.bin and bios9.bin and place them inside the selected folder on the bios and firmwares customizations option!

**Comment by shabbirmahmud** [comment]
Use the latest version if you face any bios and roms releated problems.

**Comment by karlsefinn** [comment]
> Use the latest version if you face any bios and roms releated problems.

err... i use the latest version bro, and what i said earlier was purely to solve my issue, and yeah, it solved it, but thanks for the advice

**Comment by shabbirmahmud** [comment]
> err... i use the latest version bro, and what i said earlier was purely to solve my issue, and yeah, it solved it, ive just had to change the directory but it needed the bios and firmware customization, but thanks for the advice

I see u was using v1.3.0.In the latest beta [v1.4.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.4.0)the emulator can load rom inside the download folder.It can run roms without custom bios.No white screen issus.You can try by turning off custom bios.You can also use custom bios also in the emulator settings.

**Comment by rafaelvcaetano** [comment]
> So when chosing rom path did you a system file manager
> I have the same issue when using using android 10
> This path is an issue that I don't know why anything even exists
> 
> romSearchDirUri=content://com.android.providers.downloads.documents/tree/downloads
> anything that has the android path that starts with this com.android.providers.downloads.documents there are other issues related to this.
> Id recommend using material files as a selecter
> 
> @rafaelvcaetano. Is it possible to re-`nable the sekection dialog from 1.1 alpha as another app called limbo emulator has a similar issue but I fixed by using the legacy file picker

Using the old file selector is no longer viable with the new storage restrictions that are being enforced since Android 11. From now on, using URIs to locate files (instead of using file paths) is the only way to guarantee that everything works as expected. The problems with previous app versions was that URIs were being converted to file paths and, since different devices have different storage implementations, it would not always work as expected.

**Comment by strikersix23** [comment]
I suggested that for android 10 and below

**Comment by rafaelvcaetano** [comment]
But that would mean supporting 2 different systems, which is far from ideal. And since using the Storage Access Framework is required for future versions and it's backwards compatible up to Android 5, it's simply better to make sure this implementation works properly than splitting the effort.
