### ISSUE TITLE
Can't press A button

### ISSUE THREAD

**Issue by alwaysdimdim** [rafaelvcaetano/melonDS-android#256]
Could you please add a button edit feature in this emulator I can't press the A and R buttons

**Comment by shabbirmahmud** [comment]
Already has bro in emulator settings.
![Screenshot_2021-03-29-10-14-15-59](https://user-images.githubusercontent.com/47573399/112786240-a04f6d80-9077-11eb-8c7c-588dc7bdea8c.jpg)
![Screenshot_2021-03-29-10-14-25-16](https://user-images.githubusercontent.com/47573399/112786246-a34a5e00-9077-11eb-8710-c11f29279876.jpg)

**Comment by alwaysdimdim** [comment]
sorry I am not careful in looking for it😅

Pada tanggal Sen, 29 Mar 2021 11.15, Shabbir Mahmud <
***@***.***> menulis:

**Comment by alwaysdimdim** [comment]
#
