### ISSUE TITLE
help bios dsi

### ISSUE THREAD

**Issue by Tonystarsyt** [rafaelvcaetano/melonDS-android#257]
![Screenshot_20210329-005226_melonDS.jpg](https://user-images.githubusercontent.com/78982803/112797784-242e3900-9029-11eb-8b0a-b0058c6bb5bb.jpg)

**Comment by shabbirmahmud** [comment]
Nand.bin file is missing in your dsi bios folder.Or maybe you have to renaming it.You can play the games without dsi bios.

**Comment by Tonystarsyt** [comment]
😔

**Comment by shabbirmahmud** [comment]
> 😔

The game will work without the dsi bios.

**Comment by shabbirmahmud** [comment]
Can u sent me a screenshot of your dsi bios folder?
