### ISSUE TITLE
Facing Problems On Redmi 5+ In Android 11 Beta v1.4.0 

### ISSUE THREAD

**Issue by shabbirmahmud** [rafaelvcaetano/melonDS-android#259]
Local multiplayer is not working in Redmi 5+ beta v1.4.0.It's working on beta v1.3.0.Check this video-https://youtu.be/Y105vqm0pyE

![Screenshot_20210330-045914_Settings](https://user-images.githubusercontent.com/47573399/112910722-d0e5e480-9115-11eb-844f-1c77d800d386.png)

I can't select this folders for rom and bios directory in Android 11.But I can in Android 10.

![Screenshot_20210330-050058_Files](https://user-images.githubusercontent.com/47573399/112910797-f70b8480-9115-11eb-91a9-53f8782b90b9.png)
![Screenshot_20210330-050107_Files](https://user-images.githubusercontent.com/47573399/112910801-fa9f0b80-9115-11eb-8765-d5107e5dd419.png)
![Screenshot_20210330-050116_Files](https://user-images.githubusercontent.com/47573399/112910806-fd016580-9115-11eb-95ac-2fd2beb8ea4c.png)

**Comment by rafaelvcaetano** [comment]
You can select folders but not at the storage root (the Download folder is considered a root folder). This is a change in Android 11 and since I updated the SDK to match that, this is working as intended. You should still be able to select other folders.

I will see what's wrong with multiplayer.

**Comment by shabbirmahmud** [comment]
> You can select folders but not at the storage root (the Download folder is considered a root folder). This is a change in Android 11 and since I updated the SDK to match that, this is working as intended. You should still be able to select other folders.

Oh that's why.Thanks for the information.

> I will see what's wrong with multiplayer.

Thanks 😊

**Comment by rafaelvcaetano** [comment]
I just tested and I managed to complete a trade between 2 Pokémon games (the first successfull one, yay!). I was using the internal firmware. Since you are using a custom BIOS, if both instances use the same files, try to enable "Randomize MAC address" in one instace.

**Comment by shabbirmahmud** [comment]
Yea it worked i tuned on randomize mac address in one emulator.

> I was using the internal firmware. Since you are using a custom BIOS

Its possible to trade using internal firmware.But without the custom firmware there is no way to tranfer pokemon from gen 4 to gen 5 coz its need ds download play.

>I just tested and I managed to complete a trade between 2 Pokémon games (the first successfull one, yay!).

It was possible in v1.3.0 too.I can now transfer pokemon from gen 4 to gen 5 using ds download play.It wasn't possible in v1.3.0.Now the performance is incresed than before.Thats why the game is saving.I shared it in discussion #66

You can now close this issu

**Comment by shabbirmahmud** [comment]
I just transferred 6 pokemons from gen 4 to gen 5 in my redmi 5+ too.Its working.Now i can transfer all my old gen pokemon to newer gen.Thanks for making the emulator.I really really appreciate it🥰😘
