### ISSUE TITLE
Sound is higher pitched than the PC version or a real DS

### ISSUE THREAD

**Issue by tomrow** [rafaelvcaetano/melonDS-android#26]
The sound in this version of the emulator seems to be played somewhat higher in pitch than the PC verison of MelonDS, DraStic on the same phone or a real DS.

The device I'm using is a Samsung Galaxy S10+ with an Exynos chipset.

**Comment by rafaelvcaetano** [comment]
The sound output is now resampled, like in the PC version. Can you check if it's better?

**Comment by tomrow** [comment]
It's pretty on point now!
