### ISSUE TITLE
Remove this top bar(layouts)

### ISSUE THREAD

**Issue by shabbirmahmud** [rafaelvcaetano/melonDS-android#262]
This bar is annoying sometimes while editing layouts
![IMG_20210330_170648](https://user-images.githubusercontent.com/47573399/112981985-be06fa80-917d-11eb-82ff-ab04794d1d81.jpg)

**Comment by shabbirmahmud** [comment]
I found another bug.It happens when i edit the layout then turn on split screen.And again turn off the split screen.The buttons,screens all vanishes.Stay a black screen.

https://user-images.githubusercontent.com/47573399/113089400-67470280-9209-11eb-85ef-a3ed97bfaa4a.mp4

**Comment by rafaelvcaetano** [comment]
This should be fixed in the [Beta 1.5.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.0) release.

**Comment by shabbirmahmud** [comment]
> This should be fixed in the [Beta 1.5.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.0) release.

Yes now it fixed.The bar is not coming anymore.Thanks😊.
