### ISSUE TITLE
Add integer values in buttons size(layouts)

### ISSUE THREAD

**Issue by shabbirmahmud** [rafaelvcaetano/melonDS-android#263]
Please add integer values here.I cant resize the buttons properly.Some becomes bigger,some smaller.
![Screenshot_2021-03-30-17-34-31-65](https://user-images.githubusercontent.com/47573399/112982443-51d8c680-917e-11eb-9de7-5e31a18267db.jpg)

**Comment by rafaelvcaetano** [comment]
In version [Beta 1.5.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.0) you can now see the size of the component in pixels.

**Comment by shabbirmahmud** [comment]
> In version [Beta 1.5.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.0) you can now see the size of the component in pixels.

Yes it helps a lot to resize the components perfectly.Thanks😊.
