### ISSUE TITLE
Can't rename and delete the layouts

### ISSUE THREAD

**Issue by shabbirmahmud** [rafaelvcaetano/melonDS-android#266]
Can't delete the extra layouts when i don't need that.And also can't rename when i mistype something.Please fix it.

**Comment by HJMBgit84** [comment]
I agree with this buddy it is really needed :)

**Comment by rafaelvcaetano** [comment]
In version [Beta 1.5.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.0) you can now rename and delete layouts.

**Comment by shabbirmahmud** [comment]
Editing the layout name is little bit of annoying to go to property section.It would be if we could rename from outside.But this will do too.Thank u so much😍.
