### ISSUE TITLE
Function requirement: Screenshots in save-states

### ISSUE THREAD

**Issue by android-1995** [rafaelvcaetano/melonDS-android#274]
need a screenshot of the game.
thank you

**Comment by rafaelvcaetano** [comment]
What kind of screenshot? Can't you just use the device's built-in screenshot feature?

**Comment by android-1995** [comment]
It’s better to have screenshots in the save state, so that you can see it intuitively.
the device's built-in screenshot feature have other views, only screenshots of the game will be better

**Comment by shabbirmahmud** [comment]
> It’s better to have screenshots in the save state, so that you can see it intuitively.
> the device's built-in screenshot feature have other views, only screenshots of the game will be better

Then u should change the title to save states screenshot.

**Comment by shabbirmahmud** [comment]
You want this right?

![Screenshot_2021-04-01-06-59-37-13](https://user-images.githubusercontent.com/47573399/113229054-fdd1fd00-92b7-11eb-909b-ccff4617afa6.jpg)

**Comment by android-1995** [comment]
> You want this right?
> 
> ![Screenshot_2021-04-01-06-59-37-13](https://user-images.githubusercontent.com/47573399/113229054-fdd1fd00-92b7-11eb-909b-ccff4617afa6.jpg)

yes

**Comment by rafaelvcaetano** [comment]
Support for this has been added in the Beta 1.7.0 release.
