### ISSUE TITLE
Melonds has updated code

### ISSUE THREAD

**Issue by HJMBgit84** [rafaelvcaetano/melonDS-android#28]
Melonds has updated code, I wonder if you will update your app dinner, do you?

**Comment by rafaelvcaetano** [comment]
I hope so but these things take time. Please be patient.

**Comment by HJMBgit84** [comment]
> I hope so but these things take time. Please be patient.

Ok no problem, thanks for your work 👍

**Comment by Paraskevidis** [comment]
Is this still being worked on? I want a melonds on android so bad because of the potential multiplayer and DSi emulation which is missing from android ds emulators. Is it could connect to dolphin for android to do ds to Wii connectivity that would be even more superb
