### ISSUE TITLE
FIX Load Rom Folder Download 

### ISSUE THREAD

**Issue by andrajackboy085** [rafaelvcaetano/melonDS-android#280]
![Screenshot_20210403-033738_One UI Home](https://user-images.githubusercontent.com/81408724/113452790-f1bc7b80-942e-11eb-9028-10254c97e3ae.jpg)
Not work Force close

**Comment by andrajackboy085** [comment]
All storage folder no download pls update

**Comment by rafaelvcaetano** [comment]
Need more info. When does it crash?

**Comment by shabbirmahmud** [comment]
> All storage folder no download pls update

Still can't u load the rom from download folder?Use the latest [v1.4.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.4.0)

**Comment by rafaelvcaetano** [comment]
Closed due to lack of feedback.
