### ISSUE TITLE
Is there any to convert .dss to .ml1?

### ISSUE THREAD

**Issue by shabbirmahmud** [rafaelvcaetano/melonDS-android#283]
I want to convert my all old savestate .dss file from drastic to melonds.But melonds supports .ml1 file.Is there any way to convert .dss to .ml1?

**Comment by rafaelvcaetano** [comment]
Sorry but no way this can be done. Save-states are entirely dependent on the structure of the emulator and each one implements them on their own way.

**Comment by shabbirmahmud** [comment]
So sad 😢. Nothing can be done then.

**Comment by shabbirmahmud** [comment]
I think there is a way.I have to just load the .dss file in drastic and save the game to .dsv and then convert iit to .sav.After then i will save state that saves.Very lengthy process though.
