### ISSUE TITLE
File Access Denied on Android 10

### ISSUE THREAD

**Issue by mn26** [rafaelvcaetano/melonDS-android#3]
Android >=10 uses a different system for external storage access. File browser in app doesn't work because of this. A quick fix is to add `android:requestLegacyExternalStorage="true"` to manifest. I tested this in my fork and it seems to work.

**Comment by rafaelvcaetano** [comment]
Thank you for your investigation! A new version has been released with your suggested fix. I'll close this issue and we will keep the discussion on #2.
