### ISSUE TITLE
"No apps can perform this action" when attempting to change layouts or key mappings.

### ISSUE THREAD

**Issue by Dionicio3** [rafaelvcaetano/melonDS-android#305]
* **Device model:** Google Pixel 3 XL
* **Android version:** Android 10

**Problem:**  
Whenever you try to edit layouts or key bindings, you get an empty app selection menu that says "No apps can perform this action" on it.

**Steps to reproduce (if applicable):**
1. Attempt to edit layout or key bindings
![Screenshot_20210426-001354](https://user-images.githubusercontent.com/61460279/116043820-00104880-a625-11eb-953c-55409aa3eb59.png)

**Comment by rafaelvcaetano** [comment]
Fixed in the [Beta 1.5.1](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.1) release. If you still encounter problems, please open a new issue.
