### ISSUE TITLE
Bad Performance, some games not recognized

### ISSUE THREAD

**Issue by ariebe9115** [rafaelvcaetano/melonDS-android#31]
The performance is still bad for cheaper devices, i tested it on amazon fire 7 2017 that runs at 10fps and on samsung galaxy A20e that runs with 25 FPS, would still like a good performance while using your app that is good, by the way some nds games arent recognized

**Comment by rafaelvcaetano** [comment]
Sorry for kind of ignoring this issue. Performance has been improving in the latest versions so give that a try if you haven't already. Also, if some games are still not being recognized, feel free to open a new issue describing what's going in better detail.
