### ISSUE TITLE
audio becomes silence when connecting/disconnecting earphones

### ISSUE THREAD

**Issue by pokegamer5547** [rafaelvcaetano/melonDS-android#320]
When connecting/disconnecting the earphones,the audio becomes silence. It probably isn't switching the audio output. Restarting the game fixes the problem.

**Comment by AllwinAristo** [comment]
I also affect while screen recording.

**Comment by rafaelvcaetano** [comment]
This should be fixed in the [Beta 1.6.0](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) release. Let me know if you have further problems.
