### ISSUE TITLE
MelonDS wi-fi problem

### ISSUE THREAD

**Issue by Flamehere** [rafaelvcaetano/melonDS-android#339]
**********************

* **Device model:** <SM-A405FN>

* **Android version:** <10>

**Problem:**  
Funciona todo corectamente hasta el final donde se bloquea

Add screenshots if the issue can be visualized.
![20210509_200426](https://user-images.githubusercontent.com/83078875/117582495-87b88580-b102-11eb-9586-885aedf0a703.jpg)

**Comment by Flamehere** [comment]
Los sprites de los pokemon desaparecen y la musica sigue sonando,
El melonds clonado actua como la version anterior al 1.5.1.

**Comment by Flamehere** [comment]
@rafaelvcaetano ke debo hacer?

**Comment by Flamehere** [comment]
No se porque anque intente usar versiones antiguas es como si se sincronizaran

**Comment by rafaelvcaetano** [comment]
Eh estado investigando el problema. Pero aún no sé cual sea el problema y por ahora no tengo ninguna solución.

**Comment by Flamehere** [comment]
Mmhh ok

**Comment by Flamehere** [comment]
@rafaelvcaetano oye amigo vi ke actualizastes melonds,te puedo preguntar como hacer que melonds no tenga lag.por la mayoria los fps son 60 pero de ves en quando los fps caen.hay alguna forma de aumentar la calidad,si no pues no hay problema

**Comment by rafaelvcaetano** [comment]
Además de activar el JIT y la opción "Threaded rendering", no hay ninguna configuración más que pueda mejorar el rendimiento.

**Comment by Flamehere** [comment]
Ah ok gracias de todas formas

**Comment by shabbirmahmud** [comment]
Try this-
Those who are facing communication error while locally trade. Watch this video-https://youtu.be/ai-wo5CIIQ8
Turn off filtering. Turn on randomized mac address on both emulators. Turn on fast forward after booting the game. Idk what made the difference. Bt it is working for some users who was getting communication error.
