### ISSUE TITLE
Cannot view roms from external SD card

### ISSUE THREAD

**Issue by Sebby37** [rafaelvcaetano/melonDS-android#34]
When setting the rom directory, it only allows me to select from my internal storage instead of my SD card

**Comment by rafaelvcaetano** [comment]
Release Beta 1.0.0 should add support for SD cards. Let me know if it works for you.

**Comment by Sebby37** [comment]
It works and I can now use bios files and rom files from my sd card and internal storage. It also appears to run a decent bit better now.
