### ISSUE TITLE
buttons problem

### ISSUE THREAD

**Issue by prolegond** [rafaelvcaetano/melonDS-android#349]
I have problem , i cant change move buttons to right or left , only up and down , i tried many version but nothing happened , i hope it gets fixed as soon as possible . 
![Screenshot_2021-05-14-11-54-35-80](https://user-images.githubusercontent.com/84184685/118268728-4b43ab80-b4ad-11eb-8a72-60cab442a35b.png)
![Screenshot_2021-05-14-11-52-59-68](https://user-images.githubusercontent.com/84184685/118268740-4da60580-b4ad-11eb-8168-9bf88fa12537.png)
![Screenshot_2021-05-14-11-52-51-57](https://user-images.githubusercontent.com/84184685/118268743-4e3e9c00-b4ad-11eb-875d-7eb3ddc00f32.png)

**Comment by rafaelvcaetano** [comment]
I've never see such behaviour. Could you give me more details? More specifically:
- When you open the layout editor do the buttons appear in their default locations?
- When you click on a button, what happens? Does it move immediately or does it stay in place?
- When you drag a button, what happens exactly? Does the button snap to the side? Or does it move to the side as you drag your finger on the screen?

**Comment by rafaelvcaetano** [comment]
Closed due to lack of feedback.
