### ISSUE TITLE
Nintendo WFC not working

### ISSUE THREAD

**Issue by shabbirmahmud** [rafaelvcaetano/melonDS-android#35]
https://user-images.githubusercontent.com/47573399/102869593-08cdf380-4466-11eb-8460-a2222f426be4.mp4

**Comment by rafaelvcaetano** [comment]
Wi-Fi is not yet supported.

**Comment by shabbirmahmud** [comment]
> Wi-Fi is not yet supported.

Can we get the support??

**Comment by Fietoo** [comment]
Probably not for a while
