### ISSUE TITLE
External storage support and performance issues

### ISSUE THREAD

**Issue by Lucas-mother3** [rafaelvcaetano/melonDS-android#36]
Hi, When I installed melonDS for Android, I hoping that it will read my 16GB micro SD card. But it didn't work. I transferred some of my games into the internal storage and play them. The emulator is slow, like between 8-20fps. I was disappointed. Please increase the performance of your emulator for this device. 

Name: Huawei Y6 Prime 2019

**Comment by rafaelvcaetano** [comment]
The external storage issue has already been reported and should be fixed on the next release.
Regarding performance, the next release should also bring some improvements but do not expect miracles. That device is too weak to run this emulator.

**Comment by Lucas-mother3** [comment]
I don't expect it to run really fast, just like 30fps. Also can you write JIT?

**Comment by rafaelvcaetano** [comment]
JIT is already implemented and will be available in the next release. Together with threaded rendering, the performance gains are considerable (but not miraculous). It should be released shortly.

**Comment by rafaelvcaetano** [comment]
Check if the Beta 1.0.0 release works with external storage and let me know how the performance is.

**Comment by rafaelvcaetano** [comment]
Closed due to lack of feedback.
