### ISSUE TITLE
Ninetendo WFC don't remain save

### ISSUE THREAD

**Issue by shabbirmahmud** [rafaelvcaetano/melonDS-android#365]
Everytime i need to edit the the ninetendo wfc settings if i exit the game. It don't remain save even though i save them. Please fix it.

![7b01f4bf5b6df9fef18411b7c1aae1e9 0](https://user-images.githubusercontent.com/47573399/118995331-e0144080-b9a8-11eb-8419-9bd4fd30ae70.jpg)

![7b953df6e06ac00cda3f74d0430d517e 0](https://user-images.githubusercontent.com/47573399/118995328-de4a7d00-b9a8-11eb-91ae-a591ab6df734.jpg)

**Comment by rafaelvcaetano** [comment]
Are you using the internal BIOS and firmware or a custom one?

**Comment by shabbirmahmud** [comment]
Internal bios. Oh thats why thanks😊
