### ISSUE TITLE
Thanks for Beta 1.0.0 but touchscreen issue

### ISSUE THREAD

**Issue by HJMBgit84** [rafaelvcaetano/melonDS-android#37]
Thanks for your work porting melonDS, I want to report that touchscreen does not work correctly, tried play mario kart and keeping the A button pressed the car does not Avance and stops and also the left button dpad does not respond as it should.
Kindest regards dev.

**Comment by rafaelvcaetano** [comment]
I could not reproduce this issue, even in Mario Kart since it's the game I use the most to test. Could you use [this homebrew](https://www.gamebrew.org/wiki/Diagnose) and see if everything works as expected (the option "Show boot screen" must be disabled)? I know the buttons are a bit small and sometimes A and B can be pressed simultaneously. I hope to add support for custom layouts eventually.

**Comment by HJMBgit84** [comment]
No bruh, sorry but it is not something related to press by error a and b, it is supposed that if I press A the car must go ahead and keeping the A pressed in the same point it goes forward and 5 or 10 seconds the car stopped even if I did not released the button A, and direction is not controllable, something is wrong, and I have tested it with both functions DS and DSi, I am not sure if you tested it with a gamepad but I am using touchscreen and goes bad :(

**Comment by rafaelvcaetano** [comment]
Could you get me a screen recording of the issue with touch pointers enabled? You can see [how to enable touch pointers here](https://android.gadgethacks.com/how-to/show-screen-touches-with-samsungs-new-built-screen-recorder-0233105/#:~:text=Step%202Enable%20Touch%20Indicators,to%20toggle%20the%20feature%20on.). This works even for non-Samsung phones but the name of the menus may be a bit different. And you can find screen recorders in the Play Store.

**Comment by HJMBgit84** [comment]
Sure, I see the touch does not respond sometimes when I press the buttons, attached is the video requested

**Comment by HJMBgit84** [comment]
Here is the video... My first youtube video Lol 
https://youtu.be/AZhiQlzaXtw

Let me know if you could see it

**Comment by HJMBgit84** [comment]
At least give me a like in youtube :)

**Comment by rafaelvcaetano** [comment]
The buttons definitively need some love. You are clicking too close the the inside edge, where it no longer considers the touch to be a button press. It has always been like this but I will try to make it better. I'll mark this issue as an improvement for future reference.

**Comment by HJMBgit84** [comment]
Yeah, appreciate your efforts on porting this emulator, thank you dev. :)

**Comment by rafaelvcaetano** [comment]
The handling of touch buttons was revised in the Beta 1.1.0 release. Let me know how it feels.

**Comment by HJMBgit84** [comment]
Hi unfortunately I cannot test it in the previous device because is dead Nubia Red Magic 5S, but in the actual device it is working correctly Poco F2 pro, thanks I think we can close this thread. thanks so much for your work :)
