### ISSUE TITLE
Will WiFi/multiplayer be implemented soon once it's gets stable? 

### ISSUE THREAD

**Issue by pokegamer5547** [rafaelvcaetano/melonDS-android#38]
Just wanted to know if it's going to be support multiplayer.

**Comment by shabbirmahmud** [comment]
Waiting for multiplayer...

**Comment by MojoJojoDojo** [comment]
Seems like everything but libslirp got implemented from upstream/official melonDS.
The RetroArch port is also missing libslirp support.
I wonder if its that diffcult to implement it? interesting.

**Comment by WaluigiWare64** [comment]
Does libslirp even have Android support?

**Comment by MojoJojoDojo** [comment]
Well I found this : 
https://android.googlesource.com/platform/external/qemu/+/refs/heads/master/slirp-android

**Comment by siddisking** [comment]
I have been a fan of pokemon since 2006 and really want to play ds pokemon games with friends.

I am a JS dev but would love to contribute on this issue if someone can give me a code walkthrough once.

**Comment by MojoJojoDojo** [comment]
> I have been a fan of pokemon since 2006 and really want to play ds pokemon games with friends.
> 
> I am a JS dev but would love to contribute on this issue if someone can give me a code walkthrough once.

Well the main MelonDS got  the code for libslirp.
Someone needs to convert it to this Android fork.

**Comment by rafaelvcaetano** [comment]
I'll close this issue since it's kind of dead and no immediate action is available. Meanwhile, you can checkout [this discussion](https://github.com/rafaelvcaetano/melonDS-android/discussions/317) where you can find some workarounds that some users found to Wi-Fi kind of usable.
