### ISSUE TITLE
No rom is opening In realme 5i in the latest stable release

### ISSUE THREAD

**Issue by shabbirmahmud** [rafaelvcaetano/melonDS-android#39]
No rom is loading and the emulator is crashing.

https://user-images.githubusercontent.com/47573399/104332021-f4878e80-5519-11eb-9fff-f7da1ffadab1.mp4

**Comment by rafaelvcaetano** [comment]
Could you show me a print screen of the settings screen in the System section?

**Comment by shabbirmahmud** [comment]
> Could you show me a print screen of the settings screen in the System section?

![Screenshot_2021-01-14-20-27-13-64_e7877f9796c3bfb5a5339f6b3513bed1](https://user-images.githubusercontent.com/47573399/104603758-edda5200-56a6-11eb-9432-67fa0d14a27d.jpg)

**Comment by shabbirmahmud** [comment]
Alpha version dont crash and can open the rom

**Comment by shabbirmahmud** [comment]
Same problem on redmi 5 plus

**Comment by shabbirmahmud** [comment]
I changed the bios7.bin,bios9.bin and firmware.bin file with the pc melonds emulator now its loading the game and just working with great speed than the alpha on realme 5i.
