### ISSUE TITLE
No me deja jugar

### ISSUE THREAD

**Issue by Cesar41-pixel** [rafaelvcaetano/melonDS-android#392]
## Read before you proceed (and delete this section before posting)
Only post the issue if you believe there is a problem with the emulator. If you have a question, feature request or other generic topic, you are encouraged to open a [Discussion](https://github.com/rafaelvcaetano/melonDS-android/discussions) instead. If you are not sure whether you are dealing with an issue or not, don't worry and post it wherever you feel is the most appropriate place.

Issues asking about online Wi-Fi will most likely be ignored and deleted since that feature is not yet implemented. You can, however, open a discussion if you believe you have valuable information to add regarding this topic.
**********************

* **Device model:** <insert your device's model here>
* **Android version:** <insert your device's Android version here>

**Problem:**  
Write a small description of the problem.

**Steps to reproduce (if applicable):**
1. Write a list of steps
2. Required for the problem
3. To appear

Add screenshots if the issue can be visualized.

**Comment by rafaelvcaetano** [comment]
Necesito información. Con esto no puedo hacer nada.

**Comment by Samu2508** [comment]
Quando eu escolho um jogo e começo a jogar, o aplicativo fecha sempre que tento jogar

**Comment by rafaelvcaetano** [comment]
Que versão da aplicação estás a usar? Garante que estás a usar a última versão que podes encontrar aquI: https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.2

**Comment by Samu2508** [comment]
Obrigado, parece q foi, só uma coisa, existe um jeito de jogar no melon com
meu save de outro emulador? Por exemplo, eu tenho pokemon platinun e
pokemon heart gold, mas no melon eu começo sempre do zero. Teria como fazer
isso?

Em qui, 17 de jun de 2021 18:59, Rafael Caetano ***@***.***>
escreveu:

**Comment by rafaelvcaetano** [comment]
Não deve haver problema. Qual é o outro emulador? Os saves têm de ter a extensão `.sav` e devem ser colocados na pasta da ROM, e ter o mesmo nome que a ROM.

**Comment by Samu2508** [comment]
Eu uso o drastic emulator e tenho save nos 2 jogos.

Em qui, 17 de jun de 2021 19:04, Rafael Caetano ***@***.***>
escreveu:

**Comment by rafaelvcaetano** [comment]
Tenta mudar o nome dos ficheros e altera a parte final, onde tem `.dsv` para `.sav`.

**Comment by Samu2508** [comment]
Ok obrigado

Em qui, 17 de jun de 2021 19:28, Rafael Caetano ***@***.***>
escreveu:

**Comment by rafaelvcaetano** [comment]
Closed due to lack of feedback.
