### ISSUE TITLE
MelonDS supports GB and GBC ?

### ISSUE THREAD

**Issue by azoreseuropa** [rafaelvcaetano/melonDS-android#4]
I know that it does GBA ROM support but what about GB and GBC as well ?

**Comment by rafaelvcaetano** [comment]
The Nintendo DS never supported GB and GBC ROMS. As such, there's no chance that they will be supported by this emulator.
Also, be aware that "GBA ROM support" means that NDS games can interact with GBA ROMs (like how Pokémon games used this feature to migrate Pokémons from older generations). Not that the emulator can run GBA ROMs.

**Comment by azoreseuropa** [comment]
Ahh, I understand. Thank you very much. I shall close it now. Thank you!
