### ISSUE TITLE
manage to play mario kart ds in two players 

### ISSUE THREAD

**Issue by Tonystarsyt** [rafaelvcaetano/melonDS-android#407]

**Comment by Tonystarsyt** [comment]
![Screenshot_20210607-173414_melonDS.jpg](https://user-images.githubusercontent.com/78982803/121100448-1af2e280-c7b7-11eb-9175-ae54174ad3ce.jpg)

**Comment by shabbirmahmud** [comment]
Did you able to play online or locally on two android devices?
