### ISSUE TITLE
Drastic Ds Emulator Save file is not working on latest beta release

### ISSUE THREAD

**Issue by shabbirmahmud** [rafaelvcaetano/melonDS-android#41]
https://youtu.be/orkeLCqa69k
#39

**Comment by rafaelvcaetano** [comment]
DraStic uses different file formats for save files. DraStic uses .dsv files while melonDS uses .sav files. However, I'm sure there are tools to convert between them.

**Comment by shabbirmahmud** [comment]
Bt the alpha release supports the drastic save file without converting.I just rename the extension to .save formate.

**Comment by shabbirmahmud** [comment]
I converted the .dsv save file to .save file using this online converter.Now its working on melonds.
http://www.save-editor.com/tools/wse_ds_save_converter_for_emulator_desmume_dsv.html

**Comment by Joai27373** [comment]
queria uma ajuda de vocês, meu drastick baixei ele da playstore tudo certinho, porém ele não tá reconhecendo os jogos e tanbem não está lendo os jogos no pendrive  podem me ajudar a resolver isso?
