### ISSUE TITLE
[Feature Request] Add landscape layout rotation on settings and higher resolution option

### ISSUE THREAD

**Issue by Gamemulatorer** [rafaelvcaetano/melonDS-android#422]
## Read before you proceed (and delete this section before posting)
Only post the issue if you believe there is a problem with the emulator. If you have a question, feature request or other generic topic, you are encouraged to open a [Discussion](https://github.com/rafaelvcaetano/melonDS-android/discussions) instead. If you are not sure whether you are dealing with an issue or not, don't worry and post it wherever you feel is the most appropriate place.

Issues asking about online Wi-Fi will most likely be ignored and deleted since that feature is not yet implemented. You can, however, open a discussion if you believe you have valuable information to add regarding this topic.
**********************

* **Device model:** <REDMI NOTE 9>
* **Android version:** <10>

Just like this
![Screenshot_2021-06-13-00-32-55-858_com dsemu drastic](https://user-images.githubusercontent.com/37603562/121783079-54748500-cbdf-11eb-8cfa-4fef05f57c6f.jpg)
![Screenshot_2021-06-13-00-36-23-156_com dsemu drastic](https://user-images.githubusercontent.com/37603562/121783101-681feb80-cbdf-11eb-8dd6-ad33084bc1f4.jpg)

**Comment by rafaelvcaetano** [comment]
High resolution rendering will come with the OpenGL renderer.

And melonDS already supports landscape layouts. What do you mean exactly with this exaclty? Force an orientation independently of the device's orientation? For example, force a portrait layout even if the device is in landscape mode?

**Comment by Gamemulatorer** [comment]
> High resolution rendering will come with the OpenGL renderer.

Nice I can't wait for it XD

> And melonDS already supports landscape layouts. What do you mean exactly with this exactly? Force an orientation independently of the device's orientation? For example, force a portrait layout even if the device is in landscape mode?

Yes!

**Comment by shabbirmahmud** [comment]
>High resolution rendering will come with the OpenGL renderer.

Yay🤸🤸

**Comment by AllwinAristo** [comment]
> High resolution rendering will come with the OpenGL renderer.
> 
> And melonDS already supports landscape layouts. What do you mean exactly with this exactly? Force an orientation independently of the device's orientation? For example, force a portrait layout even if the device is in landscape mode?

It means,openGL render will available in future updates or available in beta 1.6.0?

**Comment by DatEmulationGuy** [comment]
Wait, is this emulator using Vulkan now?

**Comment by Gamemulatorer** [comment]
> Wait, is this emulator using Vulkan now?
NO, i don't think there's a plan for VK backend
>As for high resolutions will there be many options?
Until OGL backend is implemented.

**Comment by DatEmulationGuy** [comment]
> > Wait, is this emulator using Vulkan now?
> 
> NO, i don't think there's a plan for VK backend
> 
> > As for high resolutions will there be many options
> 
> Until OGL backend is implemented.

I'm confused, if it's not using Vulkan or OpenGL then what is this emulator using now?

**Comment by Gamemulatorer** [comment]
> > > Wait, is this emulator using Vulkan now?
> > 
> > 
> > NO, i don't think there's a plan for VK backend
> > > As for high resolutions will there be many options
> > 
> > 
> > Until OGL backend is implemented.
> 
> I'm confused, if it's not using Vulkan or OpenGL then what is this emulator using now?

Software renderer.

**Comment by DatEmulationGuy** [comment]
> > > > Wait, is this emulator using Vulkan now?
> > > 
> > > 
> > > NO, i don't think there's a plan for VK backend
> > > > As for high resolutions will there be many options
> > > 
> > > 
> > > Until OGL backend is implemented.
> > 
> > 
> > I'm confused, if it's not using Vulkan or OpenGL then what is this emulator using now?
> 
> Software rendering [#397 (comment)](https://github.com/rafaelvcaetano/melonDS-android/issues/397#issuecomment-882125348)

Thanks, some useful links and replies there

**Comment by Gamemulatorer** [comment]
Closing and waiting for opengl backend :)
