### ISSUE TITLE
Question: where Melon Ds written in which programming language

### ISSUE THREAD

**Issue by lucariokalos** [rafaelvcaetano/melonDS-android#426]
It's written in Python, Java script, ruby or  other programming language?

**Comment by rafaelvcaetano** [comment]
You can find language statistics in the repository's main page. The emulator is written in C/C++ and the Android frontend is written in Kotlin.

Emulator:
![image](https://user-images.githubusercontent.com/9086379/122025243-1cc53300-cdc1-11eb-91de-95ff39afc1e5.png)

Android frontend:
![image](https://user-images.githubusercontent.com/9086379/122025304-2f3f6c80-cdc1-11eb-9a8b-27b8bb9382b6.png)
