### ISSUE TITLE
game restarts upon theme change

### ISSUE THREAD

**Issue by pokegamer5547** [rafaelvcaetano/melonDS-android#429]
* **Device model:** <redmi note 9 pro>
* **Android version:** <android 10 miui 12>

**Problem:**  
Game restarts when the app theme gets changed by system or in melon ds sertings.

**Steps to reproduce (if applicable):**
1. Set theme to system default in device settings
2. Run a game on melon ds
3. Change the theme in quick settings toggle and melon ds restarts the game. (Also if you manually open settings while game is running and change theme also does that)

**Comment by rafaelvcaetano** [comment]
This was fixed in the [Beta 1.6.0](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) release. Let me know you still have problems.
