### ISSUE TITLE
Save files not being detected by melonds

### ISSUE THREAD

**Issue by NitroNick-exe** [rafaelvcaetano/melonDS-android#46]
Melonds won't detect saves (yes they are named after the .nds and also are .sav) even if generated by the application itself it refuses to load them

**Comment by rafaelvcaetano** [comment]
Where did you put your save files? And how have you configured melonDS to use save files? Could you show me a screenshot of the Settings screen in the Save Files section? Also, be aware that melonDS only supports raw .sav files.

**Comment by NitroNick-exe** [comment]
I have indeed configured the save file path, here's what the settings currently look like
![Screenshot_20210119-132227](https://user-images.githubusercontent.com/68208220/105082588-6c454400-5a59-11eb-9fa8-4c8c9b1e6f92.png)

**Comment by NitroNick-exe** [comment]
Additionally, I made sure the save file was in this location it indeed is.

**Comment by NitroNick-exe** [comment]
While save next to rom file is indeed enabled, the save and rom are in the same location

**Comment by NitroNick-exe** [comment]
While I realize save to ROM location is enabled, the ROM and save are in the same directory

**Comment by NitroNick-exe** [comment]
It's been 2 days, have you figured out what the problem is?

**Comment by rafaelvcaetano** [comment]
Not yet. Are the save files placed in the SD card or in the internal storage?

**Comment by NitroNick-exe** [comment]
Internal storage

**Comment by rafaelvcaetano** [comment]
Apparently, there are some games for which melonDS cannot "locate" save files. My suggestion is to try to replicate the issue on PC and, if verifiable, open an issue on their repository with the name of the game.

**Comment by NitroNick-exe** [comment]
Thanks, will do.
