### ISSUE TITLE
Pokemon Black Broken Savestate

### ISSUE THREAD

**Issue by Gamemulatorer** [rafaelvcaetano/melonDS-android#460]
## Read before you proceed (and delete this section before posting)
Only post the issue if you believe there is a problem with the emulator. If you have a question, feature request or other generic topic, you are encouraged to open a [Discussion](https://github.com/rafaelvcaetano/melonDS-android/discussions) instead. If you are not sure whether you are dealing with an issue or not, don't worry and post it wherever you feel is the most appropriate place.

Issues asking about online Wi-Fi will most likely be ignored and deleted since that feature is not yet implemented. You can, however, open a discussion if you believe you have valuable information to add regarding this topic.
**********************

* **Device model:** <insert your device's model here>
* **Android version:** <insert your device's Android version here>
Redmi Note 9 Android 10
**Problem:**  
Write a small description of the problem.
After saving it via savestate and then load the savestate the game is freeze and can't continue to play it but I can hear the background music 🤔

Add screenshots if the issue can be visualized.
![Screenshot_2021-06-29-09-45-19-321_me magnum melonds](https://user-images.githubusercontent.com/37603562/123724734-6c2a5980-d8bf-11eb-8f72-9ad148769072.jpg)
![Screenshot_2021-06-29-09-50-38-927_me magnum melonds](https://user-images.githubusercontent.com/37603562/123724771-7ea49300-d8bf-11eb-80a0-19e65d636a89.jpg)
![Screenshot_2021-06-29-09-45-32-969_me magnum melonds](https://user-images.githubusercontent.com/37603562/123724645-44d38c80-d8bf-11eb-82f3-98e1d37ec6da.jpg)

**Comment by Gamemulatorer** [comment]
@rafaelvcaetano where I can find my savestate file?

**Comment by rafaelvcaetano** [comment]
> @rafaelvcaetano where I can find my savestate file?

It depends on your settings. If you haven't changed anything, you can find them in the same directory as your save files, which should also be the same directory your files are in. If you can't find them, give me a screenshot of your emulator's settings showing the the "Save Files" section.

**Comment by Gamemulatorer** [comment]
Ok here's my savestates file for pokemon black
[MelonDS_SaveStates.zip](https://github.com/rafaelvcaetano/melonDS-android/files/6732378/MelonDS_SaveStates.zip)
June 21 2021 has the one with broken savestate

**Comment by Gamemulatorer** [comment]
I think it could be better if the directory of the game roms and savestates are separate like any other emulator like ppsspp 🤔

**Comment by Gamemulatorer** [comment]
Oops.. melonDS already have this settings didn't see it 🤣
![Screenshot_2021-06-29-19-19-10-175_me magnum melonds](https://user-images.githubusercontent.com/37603562/123788811-05349100-d90f-11eb-985d-c4b8a4d1bce0.jpg)

**Comment by Gamemulatorer** [comment]
I try also to disable jit but loading the savestate still freeze :(

**Comment by Gamemulatorer** [comment]
Here's my log for MelonDS hope you found something useful on that log that cause the issue on savestate :)
[logs-2021-07-13-02-58-53.zip](https://github.com/rafaelvcaetano/melonDS-android/files/6803783/logs-2021-07-13-02-58-53.zip)

**Comment by Gamemulatorer** [comment]
@rafaelvcaetano in-game save data doesn't work on the latest beta v1.7.0 but the previous works fine.

https://user-images.githubusercontent.com/37603562/142950677-fc57f8b9-36af-469d-9f9c-7e91887edde4.mp4
