### ISSUE TITLE
Boot Issues

### ISSUE THREAD

**Issue by ShipmasterJame** [rafaelvcaetano/melonDS-android#47]
I can't seem to get any of my games to work. Also DSiWare games seem to not recognize the DSi bios.

EDIT: Mario Kart DS is working but the audio is terrible despite the game running at a solid 30fps

**Comment by rafaelvcaetano** [comment]
DSiWare games cannot be booted directly. They must be installed in the NAND. You either install the game on your DSi and dump the NAND again or I'm pretty sure there are tools to help with that.

And what do you mean you cannot get any game to work? What type of games?

**Comment by ShipmasterJame** [comment]
Here are the games that won't load. They show a white screen and freeze with 0fps

The World Ends With You
Rhythm Heaven
Pokemon Black 2

**Comment by shabbirmahmud** [comment]
> Here are the games that won't load. They show a white screen and freeze with 0fps
> 
> The World Ends With You
> Rhythm Heaven
> Pokemon Black 2


Bro i tested pokemon white 2 but it worked great
