### ISSUE TITLE
Fast forward not working

### ISSUE THREAD

**Issue by AllwinAristo** [rafaelvcaetano/melonDS-android#482]
## Read before you proceed (and delete this section before posting)
Only post the issue if you believe there is a problem with the emulator. If you have a question, feature request or other generic topic, you are encouraged to open a [Discussion](https://github.com/rafaelvcaetano/melonDS-android/discussions) instead. If you are not sure whether you are dealing with an issue or not, don't worry and post it wherever you feel is the most appropriate place.

Issues asking about online Wi-Fi will most likely be ignored and deleted since that feature is not yet implemented. You can, however, open a discussion if you believe you have valuable information to add regarding this topic.
**********************

* **Device model:**honor 7x
* **Android version:** android 9

**Problem:**  
Fast forward not working and game is not smooth (both ds and dsi).while play game(3d),fps go under 30

**Steps to reproduce (if applicable):**
1. Write a list of steps
2. Required for the problem
3. To appear

Add screenshots if the issue can be visualized.

**Comment by rafaelvcaetano** [comment]
What do you mean with fast forward not working? When you press the button nothing happens? For fast-forward to take effect, your device needs to be able to run the emulator at more than 60 FPS. If you're not hitting this framerate, fast forwarding won't do anything.

**Comment by Gamemulatorer** [comment]
Please try the [Beta 1.5.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.2) where this problem was addressed. If you still encounter errors after updating, please open a new issue.

**Comment by rafaelvcaetano** [comment]
> Please try the [Beta 1.5.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.2) where this problem was addressed. If you still encounter errors after updating, please open a new issue.

No fast-forward issue was addressed in that release. I appreciate your help in answering issues that report problems in older versions, but please make sure that the comment applies.

**Comment by Gamemulatorer** [comment]
@AllwinAristo why did you close is your issues is solved using v1.5.2

**Comment by AllwinAristo** [comment]
No,but problem is low fps.
