### ISSUE TITLE
Curved screen devices

### ISSUE THREAD

**Issue by coderkei** [rafaelvcaetano/melonDS-android#50]
Hi there,

Would it be possible to add an option to move the screens down a bit? My device has curved corners which partially obscure the top screen, but since this device does not have a notch, it lacks any mode/feature in the OS to move content below the curved corners in apps.

My device is an Oppo Reno on Android 10. Thank you.

**Comment by rafaelvcaetano** [comment]
Customizable layouts are in development. They may not come in the next release, but they shouldn't be too far off.

**Comment by rafaelvcaetano** [comment]
Customizable layouts are now available and you can now position each component as you see fit.

**Comment by coderkei** [comment]
Thank you!
