### ISSUE TITLE
Game wifi crashes 

### ISSUE THREAD

**Issue by Prachethana** [rafaelvcaetano/melonDS-android#502]
Hi whenever I try to connect to wifi the game crashes pls check this

**Comment by SombraShadow** [comment]
which version did you have the problem?

**Comment by shabbirmahmud** [comment]
Your phone name?

**Comment by rafaelvcaetano** [comment]
Wi-Fi is not yet properly implemented. You can check some workarounds other users found to try to make it work. You can read more about it [in this discussion](https://github.com/rafaelvcaetano/melonDS-android/discussions/317). Meanwhile, support for Wi-Fi problems won't be provided.
