### ISSUE TITLE
can't select bios 

### ISSUE THREAD

**Issue by him506** [rafaelvcaetano/melonDS-android#51]
When i select the bios folder it gives me an error saying "incorrect bios directory"

tried multiple folders and multiple bios files (normal ds and dsi) with no luck

seems to be working on the latest alpha version but not on the beta

**Comment by rafaelvcaetano** [comment]
Are you sure that the files are correctly named? For the DS, for example, the files must have the following exact names:
- bios7.bin
- bios9.bin
- firmware.bin

Even if a single file has only one character wrong, it will tell you that the directory is not valid. After you double check everything, if the problem still persists, let me know the following:
- Device model
- Android version
- Are you placing the BIOS files in the internal storage? Or in an SD card?

**Comment by him506** [comment]
All the files are named correctly and they are on internal storage, device is huawei nova 7 on Android 10 emui

**Comment by rafaelvcaetano** [comment]
OK. This is really weird. There's not much I can do right now since it seems to be a problem specific to that device. I'll add more logs in the upcoming version to try to find out whats going on.

**Comment by rafaelvcaetano** [comment]
I just thought of one more thing. On your device, could you do these steps:
1. Go to Settings
2. Go to Apps (or the equivalent on your device)
3. Find melonDS
4. Click on "Permissions"
5. Check if the Storage Permission is enabled. If not, enable it and try again.

**Comment by shabbirmahmud** [comment]
I faced the same issu.Bt then i just uninstall the app and reinstalled the app and thats solve the problem.

**Comment by shabbirmahmud** [comment]
> I faced the same issu.Bt then i just uninstall the app and reinstalled the app and thats solve the problem for me.

**Comment by shabbirmahmud** [comment]
The new beta 1.1.1 version has released with fixed bios directory fixed.You can test it out.Maybe you don't have to give the storage permission manually.

**Comment by rafaelvcaetano** [comment]
BIOS files are no longer required as of release [Beta 1.2.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.2.0). I will close this issue.
