### ISSUE TITLE
Roms folder select bug

### ISSUE THREAD

**Issue by SuperLuigiGlitchy3** [rafaelvcaetano/melonDS-android#518]
**Problem:**  
When I select a folder containing my roms, I get back to my phone menu, then when I try to comeback to the app, I get back again to my phone menu. Why I got this?

**Comment by Gamemulatorer** [comment]
What is your phone android version?
Do you use external sscard?

**Comment by SuperLuigiGlitchy3** [comment]
Android version: 9
No, I don't use external SD card.

**Comment by rafaelvcaetano** [comment]
Which version of the emulator are you using? If you are not sure, try using the [latest version](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.2). If you are already using the latest version or if the problem is not fixed, could you record a video showing the problem?

**Comment by SuperLuigiGlitchy3** [comment]
I'm using 1.5.2, and It worked finally, sorry for disturbing.

**Comment by XiaomiRedmi9** [comment]
You can now close this...
