### ISSUE TITLE
freezes when a big zip file exists in ROMs folder

### ISSUE THREAD

**Issue by pokegamer5547** [rafaelvcaetano/melonDS-android#527]
* **Device model:** Redmi note 9 pro
*  **Android version:** Android 11 Arrow OS 11 Custom ROM with no GAPPS

**Problem:**  
I have a file named "games.zip"  which contains 5 of my games (some of which are 3ds). This file exists in a folder called "games" where my other games (DS ones along with 3DS without archived) also exists. for some reason, melon ds freezes and crashes after it finished loading roms from selected roms folder.

*Steps to reproduce (if applicable):**
1. Select the games ROMs folder and wait till it completely loads all files.(10 seconds atleast).
2. Melon DS crashes.

I'm unable to reproduce this problem with any other zip but it's fixed whenever i move away the zip file before resetting up melon ds again. So idk what really causes this. 
![48550755-a42b-434c-829a-9424a593a8d7](https://user-images.githubusercontent.com/65234485/127698980-698bbcf2-6055-48bf-ba6a-82cb21acbdb7.png)
![b359522f-aed0-4aaa-8771-3106e04ae0ac](https://user-images.githubusercontent.com/65234485/127698994-32fc7b52-dbb6-433f-b8f3-449d28a14aa9.png)
![d111d789-9680-4d0c-9ff6-6f6d00ee5805](https://user-images.githubusercontent.com/65234485/127698999-a8c96bb9-f224-4ceb-9a63-c42c46b8df11.png)
![376350f0-f2c0-44e2-85b2-e0064830e298](https://user-images.githubusercontent.com/65234485/127699000-b1bcd234-972f-4da5-9939-743d678fbff7.png)

**Comment by XiaomiRedmi9** [comment]
@pokegamer5547 are you using the latest beta apk https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.2

**Comment by pokegamer5547** [comment]
> @pokegamer5547 are you using the latest beta apk https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.5.2

Yes i am using latest build 1.5.2 from github.

**Comment by XiaomiRedmi9** [comment]
Try this https://github.com/rafaelvcaetano/melonDS-android/actions/runs/1080121056 click jobs > melonds.zip extract install apk

**Comment by rafaelvcaetano** [comment]
> Try this https://github.com/rafaelvcaetano/melonDS-android/actions/runs/1080121056 scroll down > > artifacts > melonds.zip download - extract install apk

I guess this is worth a try. I've made some changes in how compressed files are handled since the latest version.  Nothing specific to this prpblem, but you never know. And I couldn't reproduce this problem using a large file (>2GB) with multiple large files inside. The ROM list is loaded almost immediately. Let me know if that version fixes your problem.

**Comment by pokegamer5547** [comment]
@XiaomiRedmi9 @rafaelvcaetano  i've tested the artifacts build  just now and this problem exists in it too. I feel like maybe because the zip file of mine contains multiple roms (some ds and 3ds) melon ds trying to recognise what file is in zip but end up crashing. But that's just a guess.

**Comment by rafaelvcaetano** [comment]
In my tests I've also placed ROMs from different systems in the ZIP, including 3DS ROMs, but it works flawlessly. I'll see if I can find a way for you to gather more information.

**Comment by pokegamer5547** [comment]
> In my tests I've also placed ROMs from different systems in the ZIP, including 3DS ROMs, but it works flawlessly. I'll see if I can find a way for you to gather more information.

That's kinda weird, but oh ok. meanwhile i will also try to see if i can recreate the same zip file by compressing same roms and see if it still crashes. Btw should i generate adb log for melon ds so maybe i'll hint why it's happening? (I dont know how to exactly fetch melon ds log only in adb but know how to use adb log)

**Comment by rafaelvcaetano** [comment]
The problem is that this is not a crash, but an ANR (Application Not Responding), which happens when heavy work occurs in the UI. So I don't know how useful the ADB logs will be useful, but it's worth a try. You can filter logs like this:

`adb logcat me.magnum.melonds:I`

**Comment by pokegamer5547** [comment]
> The problem is that this is not a crash, but an ANR (Application Not Responding), which happens when heavy work occurs in the UI. So I don't know how useful the ADB logs will be useful, but it's worth a try. You can filter logs like this:
> 
> `adb logcat me.magnum.melonds:I`

Oh i see, i understand what you mean but yeah i think maybe we might get some hint with adb . I'll try it today once i get home.

**Comment by pokegamer5547** [comment]
I have tested making same zip file and got some information. here's the info.
I made same zip file using "Zarchiver" and it created and didn't caused any issues with melon DS. But when i made same archive using "Material files" (my default file manager app),melon ds freezed upon roms loading just like before. So i guess this is happening because of how "material files" makes zip? Idk. I tried extracting the archive files i created and checked checksum values of roms  and after extracting the zip made by material files to see if the file got corrupted or something but it turns out it's fine. Both zarchiver and material files are running at their default settings so it's not like theres any modiificationeither.  
![Screenshot_20210731-180310](https://user-images.githubusercontent.com/65234485/127740193-5c4334f8-5130-4f12-bcc1-32afa40e7bc0.png)
![Screenshot_20210731-175729](https://user-images.githubusercontent.com/65234485/127740199-84ff5577-a255-4924-87e6-c75dc898d6f1.png)

**Comment by XiaomiRedmi9** [comment]
> I have tested making same zip file and got some information. here's the info.
> I made same zip file using "Zarchiver" and it created and didn't caused any issues with melon DS. But when i made same archive using "Material files" (my default file manager app),melon ds freezed upon roms loading just like before. So i guess this is happening because of how "material files" makes zip?
So this is technically not a MelonDS issue as you said using Zarchiever compression zip is not crashing when loading zip on MelonDS

**Comment by pokegamer5547** [comment]
> > I have tested making same zip file and got some information. here's the info.
> > I made same zip file using "Zarchiver" and it created and didn't caused any issues with melon DS. But when i made same archive using "Material files" (my default file manager app),melon ds freezed upon roms loading just like before. So i guess this is happening because of how "material files" makes zip?
> 
> ### So this is technically not a MelonDS issue as you said using Zarchiever compression zip is not crashing when loading zip on MelonDS

Yeah ig so, but still  i dont get it why material files is the only case. But well i guess i better close this issue now.
