### ISSUE TITLE
Failing to put the BIOS

### ISSUE THREAD

**Issue by Nilo12-s** [rafaelvcaetano/melonDS-android#53]
Hi, I downloaded MelonDS recently, but I can't place the BIOS, do you need BIOS defined? Type: BIOS defined? I expect an answer!!

**Comment by Arisotura** [comment]
someone needs to calm down

**Comment by rafaelvcaetano** [comment]
Nice to see you drop by, Arisotura!

> Hi, I downloaded MelonDS recently, but I can't place the BIOS, do you need BIOS defined? Type: BIOS defined? I expect an answer!!

I can't really understand your problem. Could you describe the steps you have made so far to try to make it work?

**Comment by Nilo12-s** [comment]
> Que bom ver você passar por aqui, Arisotura!
> 
> > Olá, eu baixei o MelonDS recentemente, mas não consigo colocar o BIOS. Você precisa do BIOS definido? Tipo: BIOS definido? Espero uma resposta !!
> 
> Eu realmente não consigo entender o seu problema. Você poderia descrever as etapas que realizou até agora para tentar fazer isso funcionar?

Hello! Sorry for the delay in seeing the answer ...

I downloaded a BIO with the DS and DSi, created a new folder and put the DS folder inside it, then entered MelonDS, I opened the folder and put it to scan, and it didn't work, I tried the same way with the DSi and it didn't work either, I use a Redmi 7A and in other emulators they work correctly, but never I used an emulator that needs BIOS, if you have a specific package I would like to know which one, because MelonDS was an emulator that I saw on YouTube and I thought it was amazing!

**Comment by rafaelvcaetano** [comment]
Did you rename the files to match the requested ones? They need to be exactly named as follows (for DS):
* bios7.bin
* bios9.bin
* firmware.bin

**Comment by Nilo12-s** [comment]
> Você renomeou os arquivos para corresponder aos solicitados? Eles precisam ser nomeados exatamente da seguinte forma (para DS):
> 
> * bios7.bin
> * bios9.bin
> * firmware.bin

Ok, I'll try to follow in your steps and I'll tell you what happened! I'll go try, thanks!

**Comment by shabbirmahmud** [comment]
> Ok, I'll try to follow in your steps and I'll tell you what happened! I'll go try, thanks!

You can check this video.Hope this will solve you problem.
https://youtu.be/z_6dOVtPYKE

**Comment by shabbirmahmud** [comment]
The new beta 1.1.1 version has released with fixed bios directory fixed.You can test it out.Maybe you don't have to give the storage permission manually.

**Comment by rafaelvcaetano** [comment]
BIOS files are no longer required as of release [Beta 1.2.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.2.0). I will close this issue.
