### ISSUE TITLE
Requests: add 1080p or 4k resolution

### ISSUE THREAD

**Issue by lucariokalos** [rafaelvcaetano/melonDS-android#54]
It possible to implement  high resolution like HDMI on emulator?

**Comment by rafaelvcaetano** [comment]
What do you mean by that? The display already takes all available horizontal space of the device, independently of its resolution. Do you mean internal resolution? The DS resolution is 256x192 per screen and there's nothing that can be done here currently. At most, we could make use of OpenGL for improved 3D quality but the OpenGL renderer has not been ported yet.

**Comment by rafaelvcaetano** [comment]
Closed due to lack of feedback.
