### ISSUE TITLE
[Feature request] [enhancement] add internal resolution option 

### ISSUE THREAD

**Issue by MrPurple666** [rafaelvcaetano/melonDS-android#549]
So, MelonDS (and Dras***) has this option to change the internal resolution of games by 2x or even more, that would be really cool and it's a useful feature also considering that NDS has a low-resolution.

**Comment by Gamemulatorer** [comment]
Duplicate https://github.com/rafaelvcaetano/melonDS-android/issues/422

**Comment by MrPurple666** [comment]
thanks for letting me know
