### ISSUE TITLE
Error when loading DSi firmware files from SD Card

### ISSUE THREAD

**Issue by Computerdude77** [rafaelvcaetano/melonDS-android#55]
There is an issue where melonDS has this error screen when using DSi mode if the files are located on the SD card (and on other non-internal storage, it seems to just crash instead). It will do this as soon as a game is launched. I know it is not corrupted firmware because if I load the same files from internal storage, it works. What's odd is that I can load the DS firmware and roms from an SD card just fine, so I assume it is something specific to the DSi firmware.

![Screenshot_20210207-234859_melonDS 1](https://user-images.githubusercontent.com/55714746/107181275-1b61a500-69a0-11eb-873c-3eaf606c4742.jpg)

**Comment by strikersix23** [comment]
What are your phone specs

**Comment by strikersix23** [comment]
Specifically device name and Android version

**Comment by Computerdude77** [comment]
Samsung Galaxy A71 5G (SM-716U), Android 10. However,  in the time since I posted this last, I got an update that includes Android 11, and it seems to have fixed the SD Card loading error, so I will go ahead and close this issue now.

**Comment by shabbirmahmud** [comment]
Duplicate of #44

**Comment by shabbirmahmud** [comment]
Duplicate of #63
