### ISSUE TITLE
Bios Nintendo dsi

### ISSUE THREAD

**Issue by Tonystarsyt** [rafaelvcaetano/melonDS-android#56]
I have a problem when I put the bios of dsi it tells me that they are not correct I do not know how to solve it because I have tried many bios of dsi and they do not work for me they do not have a bios that works

**Comment by shabbirmahmud** [comment]
> I have a problem when I put the bios of dsi it tells me that they are not correct I do not know how to solve it because I have tried many bios of dsi and they do not work for me they do not have a bios that works

The bios have to be same like this with same name.
![Screenshot_2021-02-13-12-18-06-96_db51e592e420a9871f4a37915a68789b](https://user-images.githubusercontent.com/47573399/107843497-b1a92700-6df5-11eb-838e-f323a7979c29.jpg)

**Comment by Tonystarsyt** [comment]
I thought I was the only one @shabbirmahmud

**Comment by rafaelvcaetano** [comment]
> I have a problem when I put the bios of dsi it tells me that they are not correct I do not know how to solve it because I have tried many bios of dsi and they do not work for me they do not have a bios that works

Could you get it to work by renaming the files as shown by shabbirmahmud?

**Comment by shabbirmahmud** [comment]
> I thought I was the only one @shabbirmahmud

Sometimes the emulator dont ask for storage permission.You have to manually give the storage permission.Maybe that will solve the problem.

**Comment by Tonystarsyt** [comment]
@shabbirmahmud  gracias

**Comment by shabbirmahmud** [comment]
> @shabbirmahmud gracias

The new beta 1.1.1 version has released with fixed bios directory fixed.You can test it out.Maybe you don't have to give the storage permission manually.
