### ISSUE TITLE
Error when trying to open a DSi game

### ISSUE THREAD

**Issue by joyful-cambion** [rafaelvcaetano/melonDS-android#587]
* **Device model:** SM-M205F
* **Android version:** Android API 29
* **melonDS version:** Beta 1.6.0 PS

**Problem:**  
Black screen saying that an error has occurred.
![Screenshot_20210826-231436_melonDS](https://user-images.githubusercontent.com/74503778/131043193-4bbce2e1-1edc-4f68-8b62-93cdf099ed9e.jpg)

**Comment by AllwinAristo** [comment]
https://user-images.githubusercontent.com/87270583/131241287-4bee6692-e6fd-40be-adcb-1d6a5fe2ae0a.mp4

**Comment by WaluigiWare64** [comment]
The DSiWare tries to read its contents from NAND. You already have that title installed on the NAND which is why it is working.

**Comment by AllwinAristo** [comment]
But usa title rom not working

**Comment by AllwinAristo** [comment]
https://user-images.githubusercontent.com/87270583/131247942-7c374246-007c-43b8-a436-57187c85428e.mp4

**Comment by AllwinAristo** [comment]
Is your problem solved in 1.6.1?
