### ISSUE TITLE
Bios blank screen

### ISSUE THREAD

**Issue by Dwisantosobk** [rafaelvcaetano/melonDS-android#588]
* **Device model:** <Samsung galaxy A71>
* **Android version:** < android 11 >

**Problem:**  
When run with bios just blank screen
![Screenshot_20210827-155306_melonDS](https://user-images.githubusercontent.com/86861327/131101280-2b001e58-0974-4d8b-a4e2-dbdf2a29e502.jpg)

**Comment by SombraShadow** [comment]
Update melon ds, if the bug persists, open a new issue

**Comment by Dwisantosobk** [comment]
My melon ds is new version 1.6.1

**Comment by Dwisantosobk** [comment]
Fix with download new bios
