### ISSUE TITLE
Y button don't work

### ISSUE THREAD

**Issue by QuintusNX** [rafaelvcaetano/melonDS-android#6]
And the R button, sometimes

**Comment by rafaelvcaetano** [comment]
The Y key was indeed completely broken and the L and R keys were swapped. This will be fixed in the next release. Thank you for reporting this problem :)

**Comment by rafaelvcaetano** [comment]
Fixed in release [Alpha 1.3.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/alpha-1.3.0)
