### ISSUE TITLE
Poor optimization

### ISSUE THREAD

**Issue by CalibriLight** [rafaelvcaetano/melonDS-android#602]
* **Device model:** ZTE BLADE A530
* **Android version:** 8.0

**Problem:**  
Poor optimization - trash sound and bad fps

**Steps to reproduce:**
1. Go download pokemon/any ds game
2. Open
3. Enjoy 10 fps and trash sound

**Comment by RayyanAnsari** [comment]
You do realise that no-one will help you if all you do is trash talk the hard work that people put into free, open source projects like this.

If it's so 'trash' why don't you just buy a real DS to play your legally acquired games.

**Comment by rafaelvcaetano** [comment]
Unfortunately, there's nothing that can be done right now. The emulator is still being developed and, naturally, performance should improve with time.

Since there's no immediate action, I'll close this issue. Feel free to open another one if you have other problems.

**Comment by CalibriLight** [comment]
> You do realise that no-one will help you if all you do is trash talk the hard work that people put into free, open source projects like this.
> 
> If it's so 'trash' why don't you just buy a real DS to play your legally acquired games.

I mean **trash sound**, not **trash emulator**

**Comment by DatEmulationGuy** [comment]
Looks like your device is the only trash thing here

**Comment by rafaelvcaetano** [comment]
Come on guys. There's no point in keeping this discussion going. Not everyone can afford a powerful device and opening an issue to present the problem doesn't hurt anybody.

**Comment by Gamemulatorer** [comment]
I think it's a 32bit os phone that's why it's running slow using Melonds because currently melonds does not 32bit Jit but using drastic it can run smooth on other games.
https://gadgets.ndtv.com/zte-a530-4703

**Comment by DatEmulationGuy** [comment]
> Come on guys. There's no point in keeping this discussion going. Not everyone can afford a powerful device and opening an issue to present the problem doesn't hurt anybody.

Ok I just get annoyed when people with bad or old devices complain about performance lol. I ain't rich but got a Poco x3 Pro and enjoy top performance for a very low cost

**Comment by CalibriLight** [comment]
YEEES I FIXED THIS, I DISABLED SOUND!
