### ISSUE TITLE
Incorrect bios directory for dsi

### ISSUE THREAD

**Issue by tonytigre** [rafaelvcaetano/melonDS-android#608]
OnePlus 8t
Android 11

I've loaded the bin files several times and I've checked and rechecked the spelling. I've checked the app permissions but it actually doesn't show it as being capable of accessing internal storage the only option is for microphone permission though in the app I can select the file directory and it'll ask permission which I agree to then it says incorrect bios directory

**Comment by rafaelvcaetano** [comment]
Storage permission is no longer required. Could you show me a screenshot of your Custom BIOS and Firmware screen?

**Comment by tonytigre** [comment]
![Screenshot_20210909-191718](https://user-images.githubusercontent.com/90426453/132778828-c0c5b338-3c69-4753-9b4c-bac46dfa132e.jpg)

**Comment by rafaelvcaetano** [comment]
If you also have DSi BIOS files, then you should put them in a separate directory from the DS's BIOS files because the names of the files are equal and you will have conflicts. Put them in separate directories and try again.

**Comment by tonytigre** [comment]
I only have dsi bios. I didn't set the DS bios folder it did that one automatically

**Comment by tonytigre** [comment]
The game is dsi and I clicked boot firmware dsi. I just set default system on that menu to dsi and I get the same problem though now nand is in the list of files it says to have, which I do have.

**Comment by rafaelvcaetano** [comment]
The DS BIOS is also required to run the DSi system properly. So, you need to get the BIOS files for the DS and put them in a separate folder.

**Comment by tonytigre** [comment]
Ok now the ds menu loads but when I start the game from there it says an error had occurred press and hold power button.

**Comment by rafaelvcaetano** [comment]
Which game are you trying to run? If it's a DSiWare game, you can't boot it directly. It needs to be installed into the NAND file, which melonDS for Android can't do automatically (but will soon since that feature has recently been added to the PC version). You will need to find a third party tool to do that.

**Comment by tonytigre** [comment]
Damn ok. Well thank you for helping my with my bios. I had thought the ds bios were already in the emulator, I believe I saw that it was added in one of the recent updates, so I only put in the dsi bios. The game is four swords. How long do you think it will be till that update is ready?

**Comment by rafaelvcaetano** [comment]
I haven't even started so I don't have any ETA for it. I'll try to include it for the next release.

Regarding built-in DS BIOS, you are correct that if exists, but this BIOS does not have every feature implemented and is incompatible with the DSi.

**Comment by tonytigre** [comment]
Ok I got it working thank you.
