### ISSUE TITLE
Boot screen doesnt show up. ( I have selected a working bios )

### ISSUE THREAD

**Issue by kena006** [rafaelvcaetano/melonDS-android#616]
Device model: XE500C13-K03US
Android version: 9
MelonDS version: Beta 1.6.1 GH

Problem:
Boot screen doesnt show up
when i turn it on.

Steps to reproduce:

Open the app on version Beta 1.6.1
Set bios
Run a game or the bios

**Comment by rafaelvcaetano** [comment]
Which system are you trying to run? DS or DSi? And what is displayed? Can you provide a sceenshot?

**Comment by kena006** [comment]
When i load a game, or run the (Original) Ds bios, it just shows a white screen for a few seconds and then it loads into the system menu. (Not DSI because i cant find working bios files for it)
![Screenshot 2021-09-12 8 57 58 PM](https://user-images.githubusercontent.com/82118161/133009520-086526e2-d172-41aa-893c-e108d99e9df9.png)
![Screenshot 2021-09-12 8 58 09 PM](https://user-images.githubusercontent.com/82118161/133009528-114aaab5-0795-4c46-a558-cf050e14e435.png)

**Comment by rafaelvcaetano** [comment]
So what you mean is that the Health and Safety screen is not displayed? If so, that is a particularity of the BIOS you are using. Not all BIOS display that screen. Most likely, they were modified to bypass that.

**Comment by kena006** [comment]
Ok

**Comment by kena006** [comment]
You were right, i got new firmware and it now shows the screen.
