### ISSUE TITLE
Can't load rom when bios directory is in external storage

### ISSUE THREAD

**Issue by shabbirmahmud** [rafaelvcaetano/melonDS-android#63]
* **Device model:** Redmi 5 Plus
* **Android version:** Android API 29

**Problem:**  
Can't load rom when bios directory is in external storage.Same problem in my realme 5i too.But github issu is not opening in that phone.

**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$d: Failed to load firmware: BIOS9_BAD
	at me.magnum.melonds.ui.emulator.h$b.a(Unknown Source:54)
	at f.a.b0.e.a.a.g(Unknown Source:10)
	at f.a.a.a(Unknown Source:14)
	at f.a.b0.e.a.e$a.run(Unknown Source:2)
	at f.a.r$a.run(Unknown Source:9)
	at f.a.b0.g.j.run(Unknown Source:13)
	at f.a.b0.g.j.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```
Crash log url-https://del.dog/renestaylo

![Screenshot_20210216-120651270 (1)](https://user-images.githubusercontent.com/47573399/108024835-89b50000-704f-11eb-9050-8a536cb23f41.jpg)

Check this video-https://youtu.be/NA8U9RIYdPg

**Comment by rafaelvcaetano** [comment]
Your crash log is really useful. It shows exactly what's going on but I don't really know what is causing it. Could you try the following:

1. Go to your BIOS directory
2. Duplicate the `firmware.bin` file (copy and paste it in the same directory)
3. Rename the new copy to `firmware.bin.bak`

Then let me know if the problem persists.

**Comment by shabbirmahmud** [comment]
> Your crash log is really useful. It shows exactly what's going on but I don't really know what is causing it. Could you try the following:
> 
> 1. Go to your BIOS directory
> 2. Duplicate the `firmware.bin` file (copy and paste it in the same directory)
> 3. Rename the new copy to `firmware.bin.bak`
> 
> Then let me know if the problem persists.

As u said did it and tested on both realme 5i and redmi 5 plus.Now its loading the rom without crashing.I think the emulator don't create the firmware.bin.bak file automatically in external storage like it create in internal storage.

**Comment by shabbirmahmud** [comment]
Should i close the issu?I got the solution.Now i can use sd card for melonds bios.If there is a problem with the emulator not creating the firmware.bin.bak file in sd card then it should be fixed.Until then I can use this solution.

**Comment by rafaelvcaetano** [comment]
No, you can leave this open until I fix the problem.

**Comment by shabbirmahmud** [comment]
I recently changed my custom rom android 10 to android 11 (CorvusOs) on redmi 5 plus.Now the emulator is creating firmware.bin.bak file automatically in sd card.I did this manually in previous rom.I think this problem is device and rom specific.The file creates automatically for some and for some not.

**Comment by rafaelvcaetano** [comment]
Yeah, it must be. On every device I tested, using either internal and external storage, I could never reproduce this problem. Thanks for letting me know!

**Comment by shabbirmahmud** [comment]
Idk i just experienced a weird problem in realme 5i (stock rom).My rom and bios(Custom bios-on) directory was external storage and my rom was all in zip formate.Show boot screen was turned on.Then i tried to open pokemon soul silver and it opened bt my soul silver save file was not being detected.Then i changed the save file bt the save file was not being detected.I dont think there was a problem with my save file.Then i moved the rom and save file in internal storage download folder.Now the save was being detected.Then i thought there maybe a problem of compress rom that the emu can't detect save file in external storage.Thats why i decompressed the rom in external storage.Then i tried to open the rom.Bt its showing that the firmware rom slot was empty.Then i turned off show boot screen.Then opened the rom again bt the game was not loading and only showing a white screen.Then i cleared the data of the emulator and set it up in the same settings.Bt the problem was still there.

Then i rebooted my phone and eventually the problem was solved.Now i cant reproduce the problem anymore.Very weired.

**Comment by shabbirmahmud** [comment]
* **Device model:** RMX2030
* **Android version:** Android API 29
* **melonDS version:** Beta 1.3.0

**Problem:**  
I tried to boot dsi firmware on my realme 5i when dsi bios directory was in external storage.The dsi firmware load when dsi bios directory is in external storage.The firmware.bin.bak file creates automatically in internal storage for dsi bios.Bt if i create the firmware.bin.bak file manually in external storage it still dont load.I tried using the same bios on my redmi 5+ there the firmware is loading internal or external both without creating firmware.bin.bak file manually.I don't know how to install games on nand thats why i cant test any game or rom using dsi bios.

![Screenshot_2021-03-13-12-19-18-32](https://user-images.githubusercontent.com/47573399/111021607-db0aa200-83f7-11eb-873b-dbd4f6f2bd15.jpg)

Sometimes i get this error when try to boot the firmware when 'Enable Jit' is turned off.

![Screenshot_2021-03-13-12-14-01-79_e7877f9796c3bfb5a5339f6b3513bed1](https://user-images.githubusercontent.com/47573399/111021635-0bead700-83f8-11eb-9cde-83d78d27c1d8.jpg)


**Stack trace:**  
```
me.magnum.melonds.ui.emulator.EmulatorActivity$d: Failed to load firmware: DSI_BIOS9_BAD
	at me.magnum.melonds.ui.emulator.h$c.a(Unknown Source:67)
	at f.a.b0.e.a.a.g(Unknown Source:10)
	at f.a.a.a(Unknown Source:14)
	at f.a.b0.e.a.e$a.run(Unknown Source:2)
	at f.a.r$a.run(Unknown Source:9)
	at f.a.b0.g.k.run(Unknown Source:13)
	at f.a.b0.g.k.call(Unknown Source:0)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)

```

**Configuration:**  
```
FirmwareCrashContext(emulatorConfiguration=EmulatorConfiguration(useCustomBios=true, dsConfigDirectory=/storage/85CF-1A08/Bios Files/DS/, dsiConfigDirectory=/storage/85CF-1A08/Bios Files/Dsi/, internalDirectory=/data/user/0/me.magnum.melonds/files, fastForwardSpeedMultiplier=-1.0, useJit=true, consoleType=DSi, soundEnabled=true, micSource=BLOW, firmwareConfiguration=FirmwareConfiguration(nickname=Player, message=Hello!, language=1, favouriteColour=0, birthdayMonth=1, birthdayDay=1), rendererConfiguration=RendererConfiguration(videoFiltering=LINEAR, threadedRendering=true)), dsiBiosDirUri=content://com.android.externalstorage.documents/tree/85CF-1A08%3ABios%20Files%2FDS, dsBiosDirUri=content://com.android.externalstorage.documents/tree/85CF-1A08%3ABios%20Files%2FDsi)
```

**Comment by shabbirmahmud** [comment]
Duplicate of #97

**Comment by shabbirmahmud** [comment]
Duplicate of #44

**Comment by shabbirmahmud** [comment]
In the latest update the firmware.bin.bak file for ds and dsi bios is creating automatically in external storage in my realme 5i.And also my redmi 5+ too after i changed my custom rom.Should i close this issu?

**Comment by rafaelvcaetano** [comment]
Even if you didn't change your custom rom, the problem should be fixed anyway with the new implementation. So yeah, this can be closed.
