### ISSUE TITLE
Strange Wi-Fi behaviour

### ISSUE THREAD

**Issue by justafridge** [rafaelvcaetano/melonDS-android#635]
* **Device model:** Samsung Galaxy S10 (Exynos)
* **Android version:** Android 10
* **Application version:** Beta 1.6.1 PS

**Problem:**  
I know that Wi-Fi isn't officially supported but I'd like to report the following behaviour:
1. the Nintendo DSi Browser works properly
2. games without an SSL disable patch throw up error 20100 (nds-constraint doesn't work, error equates to a failure in verifying the SSL certificate)
3. games patched with WfcPatcher 1.6 connect to the WFC but throw up error 81010 (equating to a kick, according to Wiimmfi) after a few seconds and matchmaking appears to not work

**Steps to reproduce (if applicable):**
1. Start a game that has WFC support
2. Set your favorite DNS
3. Connect to the WFC
4. Error 20100 (game without NoSSL patch) or error 81010 (game patched with WfcPatcher 1.6)

**Notes:**
1. The following was tested mainly with Mario Kart DS but the error 20100 applies to all games that have WFC features
2. Wiimmfi's main DNS (95.217.77.151) was used in these tests but any other DNS will give the same results
3. DS firmware is irrelevant, issues occur with both internal and custom firmware, random MAC address or not
4. These issues don't occur on the Windows x64 version of the emulator (neither with unpatched or patched ROM)

**Screenshots:**
Nintendo DSi Browser:
![Screenshot_20210925-083845_melonDS](https://user-images.githubusercontent.com/61917082/134761606-4814df9e-8024-4578-8c40-44fa02890b84.jpg)

Mario Kart DS without NoSSL patch:
![Screenshot_20210925-083452_melonDS](https://user-images.githubusercontent.com/61917082/134761623-de85f2c8-9838-4974-8bcf-ea1b0be0993f.jpg)

Mario Kart DS patched with WfcPatcher 1.6:
![Screenshot_20210925-074100_melonDS](https://user-images.githubusercontent.com/61917082/134761641-00b3d298-dab9-439e-8cdd-316920de7ec2.jpg)

**Comment by justafridge** [comment]
I'm also setting up a local DWC server on my PC so that I can see the logs, I'll report further in a few hours

**Comment by justafridge** [comment]
I just saw #502 and #317, I'm locking this and moving it to discussions later, if the local DWC server tells me anything interesting

**Comment by rafaelvcaetano** [comment]
I've just seen this. That error code, as you said, is returned when you are kicked. This happens because the system is "banned" from the system. Most likely you are using BIOS files you found online and someone cheated using those same files. As such, my recommendation is to use a different BIOS set.

**Comment by justafridge** [comment]
Meanwhile self-hosted server (CoWFC) throws error 52200 (can't connect to server) on my phone, works on PC.
