### ISSUE TITLE
Pequenos poblemas

### ISSUE THREAD

**Issue by BLECKHUUD35** [rafaelvcaetano/melonDS-android#640]
Na minha opinião tenque botar modo online no jogo ficaria bem mais fácil e tá tendo falhas nos jogos e etc.

**Comment by rafaelvcaetano** [comment]
Se quiseres tentar o modo multiplayer local, podes tentar correr 2 apps no mesmo dispositivo. Podes ver como [nesta discussão](https://github.com/rafaelvcaetano/melonDS-android/discussions/66).

Relativamente ao multiplayer online, alguns utilizadores tiveram alguns resultados aplicando alguns patches às ROMs. Podes ver como [nesta discussão](https://github.com/rafaelvcaetano/melonDS-android/discussions/317).

Uma vez que não foi dada informação concreta neste issue, vou fechá-lo.
