### ISSUE TITLE
Melonds crash Everytime i try to open settings or opening a game

### ISSUE THREAD

**Issue by FrenchPrick** [rafaelvcaetano/melonDS-android#658]
* **Device model:** Samsung Galaxy A10s.
* **Android version:** Beta 1.6.1 (c775f44) GH.

**Problem:**  
The emulator started crashing Everytime I tried to open the settings or a game since I started using the latest nightly build.

**Comment by DatEmulationGuy** [comment]
Happens also on my Poco x3 Pro with Android 11 stock MIUI 12.5.2.0 and the same nightly build. In fact this is the latest nightly that didn't crash for me when opening games

https://github.com/rafaelvcaetano/melonDS-android/actions/runs/1203432925

**Comment by rafaelvcaetano** [comment]
Thanks for reporting this guys. Please try the latest nightly build and let me know if both problems are fixed.

**Comment by DatEmulationGuy** [comment]
> Thanks for reporting this guys. Please try the latest nightly build and let me know if both problems are fixed.

Fixed for me, thanks!

**Comment by FrenchPrick** [comment]
Worked for me too am gonna close this issue too
