### ISSUE TITLE
Fix the layout when the emlator is in split screen like drastic ds emulator

### ISSUE THREAD

**Issue by shabbirmahmud** [rafaelvcaetano/melonDS-android#67]
![Screenshot_2021-02-16-15-06-29-94_e7877f9796c3bfb5a5339f6b3513bed1](https://user-images.githubusercontent.com/47573399/108041459-c50ff880-7068-11eb-8256-8de6d76a6281.jpg)

![Screenshot_2021-02-16-14-47-52-73_e7877f9796c3bfb5a5339f6b3513bed1](https://user-images.githubusercontent.com/47573399/108040988-2daaa580-7068-11eb-8b06-f7b199dcb5ff.jpg)

Idea-https://github.com/rafaelvcaetano/melonDS-android/discussions/66

**Comment by rafaelvcaetano** [comment]
The screen is now vertically constrained in release [Beta 1.2.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.2.0) and should fix this.

**Comment by shabbirmahmud** [comment]
Yeah now I can use the emulator in spilit screen perfectly.But there is a problem when I try to open or close the spilit screen the game or rom restarts.This will be a problem when I forget to save the game and go to split screen and the game will be restarts.Then I have to play the game from previous save.Though no one will try to open a game or rom in split screen without a reason but it can be so annoying if happen.

**Comment by shabbirmahmud** [comment]
Should I close this issue?

**Comment by rafaelvcaetano** [comment]
Yeah. I know what the emulation reset problem is and I have to address it anyway to support customizable layouts.
