### ISSUE TITLE
It won't let me play the roms

### ISSUE THREAD

**Issue by joz2000** [rafaelvcaetano/melonDS-android#68]
* **Device model: ** COVET_PRO_LITE
* ** Android version: ** Android API 29

** Problem: **
Insert a small description of the problem.

** Stack trace: **
`` ''
me.magnum.melonds.ui.emulator.EmulatorActivity $ f

**Comment by rafaelvcaetano** [comment]
I'm sorry, but that stack trace is incomplete and I can't help you with your problem unless it is shown fully. It looks like your device applied some kind of formatting to the text. Try creating a new issue to see if it doesn't happen again and then close this one.
