### ISSUE TITLE
Rewind and Save States not working in DSi Mode

### ISSUE THREAD

**Issue by Damaj301damaj-lol** [rafaelvcaetano/melonDS-android#724]
* **Device model:** Samsung Galaxy A71 
* **Android version:** Android 11

**Problem:**  
Rewind doesn't work in DSi Mode, it causes melonDS to crash, but rewinds works fine in DS Mode.

**Steps to reproduce :**
1. Load a game in DSi Mode, doesn't matter if its a DS game or a DSiWare.
2. Try using Rewind.
3. It should hang and crash
4. Try again in DS Mode 
5. It will rewind normally like expected

Video Clip on my Google Drive (github didn't help with video upload :p):

https://drive.google.com/file/d/101lpKfE_n7Z4Lip3rgd81fs4q8ZSqVp8/view?usp=drivesdk

Thanks for your time!

**Comment by Damaj301damaj-lol** [comment]
Well im gonna expand this thread a bit,

Problem:
Save states doesn't work in DSi Mode only in DS Mode

Steps to reproduce:
1. Load game in DSi Mode
2. Make a save state 
3. Try to load it
4. Crash

Compared to the last issue, this one has a bypass

Steps to use save files in DSi Mode:
1. Make a save state in DS Mode 
2. It will load in DSi Mode without crash

**Comment by rafaelvcaetano** [comment]
Yep. Apparently, DSi save states are not supposed to be supported by melonDS. For now I believe that DSi save states need to be disabled.

**Comment by Damaj301damaj-lol** [comment]
I suppose the same is with rewind

**Comment by Damaj301damaj-lol** [comment]
> Yep. Apparently, DSi save states are not supposed to be supported by melonDS. For now I believe that DSi save states need to be disabled.

Yes, i think u should remove the option until melonDS adds support
