### ISSUE TITLE
[Feature Request] Sustained Performance Mode

### ISSUE THREAD

**Issue by Gamemulatorer** [rafaelvcaetano/melonDS-android#730]
**DuckStation**
https://github.com/stenzek/duckstation/commit/3b433d8d3ecc883cb31fa7038023f2b2b316bc11

**PPSSPP**
https://github.com/hrydgard/ppsspp/pull/9901/commits/d94351ef908451891f4a8d722da6a483f658e4bc

**Dolphin**
https://github.com/dolphin-emu/dolphin/pull/7568/commits/0184658ffca982e7710c59bc102911db9042dd72

It also great if melonDS got this feature in the next version.

**Comment by rafaelvcaetano** [comment]
This feature has already been implemented and the toggle can be found in Settings > General. However, not all devices support this feature and if your device does not support it, the setting won't be displayed.

**Comment by Gamemulatorer** [comment]
DuckStation show my phone that is supported sustained performance mode.
![Screenshot_2021-11-23-07-30-18-881_com github stenzek duckstation](https://user-images.githubusercontent.com/37603562/142950329-79157fab-431e-4ead-8695-3cf222db7ac8.jpg)
