### ISSUE TITLE
Rom error

### ISSUE THREAD

**Issue by alwaysdimdim** [rafaelvcaetano/melonDS-android#79]
![Screenshot_2021-02-21-15-29-49-76_e7877f9796c3bfb5a5339f6b3513bed1](https://user-images.githubusercontent.com/79393179/108620474-fe78a780-745e-11eb-8dc5-f20e52ce54eb.jpg)
Why melonds white screen in my device

**Comment by rafaelvcaetano** [comment]
I will need more info:
* In what mode are you running? DS or DSi? 
* Which game are you trying to run?

Additionally, could you get a screenshot of your Settings screen in the System section?

**Comment by alwaysdimdim** [comment]
I tried to play Pokemon Heartgold and I sent the rest by email

**Comment by alwaysdimdim** [comment]
Here?I'am running DS mode

Pada tanggal Min, 21 Feb 2021 19.53, Rafael Caetano <
notifications@github.com> menulis:

**Comment by rafaelvcaetano** [comment]
Does this happen after loading the ROM? Or after playing for a while? I this happens immediately after loading the ROM, I suspect you have a faulty BIOS and/or firmware.

**Comment by alwaysdimdim** [comment]
Yes, it is. this happened after loading the rom and I got the bios here:
https: //emulation.gametechwiki.com/index.php/Emulator_Files

Pada tanggal Sel, 23 Feb 2021 21.08, Rafael Caetano <
notifications@github.com> menulis:

**Comment by alwaysdimdim** [comment]
Oh i use melonds beta1,0,0 because in latest version could not detect BIOS
when i try to set

Pada tanggal Sel, 23 Feb 2021 22.02, Dimas Adi <dimasadiwb@gmail.com>
menulis:

**Comment by rafaelvcaetano** [comment]
Does it work on the newest version?

**Comment by alwaysdimdim** [comment]
Yeah i tried in melonds newest version

Pada tanggal Sel, 23 Feb 2021 22.46, Dimas Adi <dimasadiwb@gmail.com>
menulis:

**Comment by alwaysdimdim** [comment]
Pada tanggal Sel, 23 Feb 2021 22.47, Dimas Adi <dimasadiwb@gmail.com>
menulis:

**Comment by alwaysdimdim** [comment]
And this is my bios file

Pada tanggal Sel, 23 Feb 2021 22.56, Dimas Adi <dimasadiwb@gmail.com>
menulis:

**Comment by rafaelvcaetano** [comment]
Can you try a different BIOS?

**Comment by alwaysdimdim** [comment]
yes I have tried several bios on the internet but only the one I screenshot
can

Pada tanggal Rab, 24 Feb 2021 00.26, Rafael Caetano <
notifications@github.com> menulis:

**Comment by rafaelvcaetano** [comment]
Have you tried using other ROMs? If yes, do they work?

**Comment by shabbirmahmud** [comment]
Try the new [beta v1.2.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.2.2) release and check if it's solve the problem?

**Comment by shabbirmahmud** [comment]
I faced this white screen problem in my redmi 5 plus.It happened previous version of melonds.I can't remember which version.I was using ds mode abd the bios directory was in external storage.Then i tried to boot the rom and got this white screen.Bt when i turned off 'show boot screen' option the white screen problem was solved.

**Comment by shabbirmahmud** [comment]
Try the new [beta v1.2.2](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.2.2) release and check if it's solve the problem?

**Comment by shabbirmahmud** [comment]
Duplicate of #172

**Comment by shabbirmahmud** [comment]
Can you use the latest beta [v1.3.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/beta-1.3.0) and open a new issue? The latest version does not fix the problem but includes additional info that will help to find the cause.

**Comment by rafaelvcaetano** [comment]
Try the latest [Beta 1.4.0](https://github.com/rafaelvcaetano/melonDS-android/releases/latest) release. There were some problems loading ROMs under certain emulator configurations and that should be fixed. I will close this issue for now but feel free to open a new one if the problem persists.

**Comment by alwaysdimdim** [comment]
Pada tanggal Sen, 29 Mar 2021 06.38, Rafael Caetano <
***@***.***> menulis:
