### ISSUE TITLE
question 

### ISSUE THREAD

**Issue by Tonystarsyt** [rafaelvcaetano/melonDS-android#795]
can you play gba games on the emulator?

**Comment by rafaelvcaetano** [comment]
No, it's not possible to play GBA games. What is possible is using additional features in DS games that were enabled when a GBA cartridge was inserted. For example, in some Pokémon games, you can migrate Pokémon from the GBA games to the DS games by using this feature.

**Comment by Tonystarsyt** [comment]
@rafaelvcaetano OK thank you very much
