### ISSUE TITLE
Gba roms

### ISSUE THREAD

**Issue by mcoldani** [rafaelvcaetano/melonDS-android#8]
I have a problem, when i tried to star a gba rom the emulator just dont recognise idk why

**Comment by rafaelvcaetano** [comment]
This emulator cannot play GBA ROMs. They can only be used in NDS games that have some kind of integration with them (like the Pokémon games that use them to migrate Pokémon).

**Comment by mcoldani** [comment]
Thanks, and i have issues my phone is a nokia 5.1 plus helio p60, and I just tested mario kart and run so bad like 30fps, need more optimization anyway thank you so much for the port I will be careful

**Comment by rafaelvcaetano** [comment]
You are right. There are some improvements that Arisotura is adding to the PC version. Once they become available, I'll try to port them and hopefully things will improve significantly.

**Comment by mcoldani** [comment]
Thanks ♥️ i appreciate so much i will be careful about your proyect, and online? it is functional?

**Comment by rafaelvcaetano** [comment]
Not right now. Proper support for that would require rooted devices and I don't want to follow that route since a lot of users wouldn't be able to use that feature. But improvements in that area are also expected and hopefully we can reach a solution that does not require root.

**Comment by mcoldani** [comment]
Thanks for answer me.

**Comment by rafaelvcaetano** [comment]
No problem. I'm gonna close this issue to avoid clutter. Feel free to open another one if you have any  question or issue.
