### ISSUE TITLE
problema de melonds

### ISSUE THREAD

**Issue by pichu51** [rafaelvcaetano/melonDS-android#87]
## Read before you proceed (and delete this section before posting)
Only post the issue if you believe there is a problem with the emulator. If you have a question, feature request or other generic topic, you are encouraged to open a [Discussion](https://github.com/rafaelvcaetano/melonDS-android/discussions) instead. If you are not sure whether you are dealing with an issue or not, don't worry and post it wherever you feel is the most appropriate place.

Issues asking about online Wi-Fi will most likely be ignored and deleted since that feature is not yet implemented. You can, however, open a discussion if you believe you have valuable information to add regarding this topic.
**********************

* **Device model:** <insert your device's model here>
* **Android version:** <insert your device's Android version here>

**Problem:**  
Write a small description of the problem.

**Steps to reproduce (if applicable):**
1. Write a list of steps
2. Required for the problem
3. To appear

Add screenshots if the issue can be visualized. If you are dealing with a BIOS problem, please add a screenshot of your Settings screen in the System section.

**Comment by rafaelvcaetano** [comment]
No hay ninguna descripcion del problema. Voy a cerrar.
