### ISSUE TITLE
Melon ds emulator for android is always say app not installed

### ISSUE THREAD

**Issue by lucariokalos** [rafaelvcaetano/melonDS-android#9]
I trying to install the melon ds emulator it always say app not installed

**Comment by rafaelvcaetano** [comment]
In which device are you trying to install it? And which Android version are you running?

**Comment by lucariokalos** [comment]
Samsung galaxy Tab A 8.0 android 6.0.1

**Comment by rafaelvcaetano** [comment]
I couldn't find anything that may cause that problem. Can you try to install the app through ADB and show me the result? If you don't know how to do that, you can follow [this tutorial](https://www.droidviews.com/install-apk-files-using-adb-commands/). In the end, it should display an error with the failure reason.

Anyway, that device is a bit old and I can tell you right now that the emulator will run very slowly.

**Comment by lucariokalos** [comment]
What is minium requirements of emulator

**Comment by rafaelvcaetano** [comment]
To run the app you only need a device with Android 4.1 and OpenGL 2. However, to achieve acceptable performance, you will probably need a device with a Snapdragon 835 or equivalent.

**Comment by lucariokalos** [comment]
What is proccessor 32bit or 64bit?

**Comment by rafaelvcaetano** [comment]
It can run on both 32 and 64 bit processors.

**Comment by lucariokalos** [comment]
On future will run on Snapdragon 400

**Comment by rafaelvcaetano** [comment]
I really doubt it. This emulator is more focused on accuracy instead of speed. And the Snapdragon 400 is slow. Even DraStic, which is more focused on performance, should have problems running on that chip.

**Comment by rafaelvcaetano** [comment]
Could you try release [Alpha 1.3.0](https://github.com/rafaelvcaetano/melonDS-android/releases/tag/alpha-1.3.0)? It uses a different signing method and may fix your problem.

**Comment by lucariokalos** [comment]
My problem is fixed thank you😁😁
