### ISSUE TITLE
Is this the end for melonds!

### ISSUE THREAD

**Issue by ASGAMING009** [rafaelvcaetano/melonDS-android#930]
I am here to know that if have stopped working on this project or This project will get updates in later future!

**Comment by ptnnx** [comment]
This project isn't abandoned! Still work-in-progress but i can guess dev is busy in his life and also learn new codes!

**Comment by rafaelvcaetano** [comment]
It's not the end, guys! But yeah, I've been extremely busy. I wanted to resume it's development a couple of months ago, but it just wasn't possible. I have a lot of features that I want to implement but it has not been easy finding free time.

**Comment by ShipperNessity** [comment]
Hello @rafaelvcaetano! 👋 Just wanted to let you know that I'm one of your fans of your works on melonDS on Android. Always take your time in developing the app more. Though, I would want to request to add a Custom Cheats feature for the app? Just like in the DraStic that you're not limited to the XML cheat files, instead you can add cheats for your own in each game. Thanks all for your hardwork and also for your contributors.

**Comment by ASGAMING009** [comment]
Well then!
