### ISSUE TITLE
Is project on hold

### ISSUE THREAD

**Issue by strikersix23** [rafaelvcaetano/melonDS-android#933]
Is this project temporary on hold?

**Comment by Gamemulatorer** [comment]
Maybe 🤔

**Comment by Dwisantosobk** [comment]
Hi get girls friends

**Comment by strikersix23** [comment]
> Hi get girls friends
Does that mean you need one?

**Comment by rafaelvcaetano** [comment]
Alright, lets stop this. As answered in other issues and discussions, I haven't had the time to work on the project, so yes, it's kind of on hold. But it's not abandoned and I have a lot of stuff left to implement.

**Comment by strikersix23** [comment]
Ok appreciate the answer, I was just wondering. I wish you luck ln your life
