### ISSUE TITLE
DSiWare Manager do not work!

### ISSUE THREAD

**Issue by ptnnx** [rafaelvcaetano/melonDS-android#959]
* Realme 7/ pro
* Android 11

- ****When i open DSiWare Manager it will crash.****

https://user-images.githubusercontent.com/81209454/189553542-3fbcce20-bd78-4932-9668-2a9a903c41c8.mp4

**Comment by rafaelvcaetano** [comment]
Oh, damn. I know it still has a lot of issues, but I wasn't aware of this crash. Thanks for letting me know! I should push some more changes related to this feature during this coming week. I would really appreciate any testing and feedback!

**Comment by rafaelvcaetano** [comment]
But to quickly identify possible problems. Could you give me a screenshot of the app in the `Settings > System > Cusom BIOS and Firmware` screen, while having the feature enabled?

**Comment by ptnnx** [comment]
https://user-images.githubusercontent.com/81209454/189553962-00c94725-2489-4767-b68f-0050f94f56f6.mp4

**Comment by ptnnx** [comment]
I tried the latest atrifact build but the problem is still there.

**Comment by hieuk** [comment]
Can confirm this issue is still present in this nightly build:
https://github.com/rafaelvcaetano/melonDS-android/actions/runs/3357738057

**Comment by rafaelvcaetano** [comment]
Please try the latest nightly build to see if the issue has been fixed: https://github.com/rafaelvcaetano/melonDS-android/actions/runs/3788882532
