### ISSUE TITLE
melonds doesn't work on any emulator frontend

### ISSUE THREAD

**Issue by crhhahaha** [rafaelvcaetano/melonDS-android#964]
It does not have storage permissions
so melonds doesn't work on any emulator frontend
include：dig launchbox daijisho

**Comment by crhhahaha** [comment]
https://github.com/magneticchen/Daijishou/issues/74

**Comment by rafaelvcaetano** [comment]
I've left a comment on the issue you linked and, as you probably have seen, this is a melonDS issue. It will be fixed in the next release. Meanwhile, you can try using nightly builds which you can find here: https://github.com/rafaelvcaetano/melonDS-android/actions/workflows/main.yaml

**Comment by crhhahaha** [comment]
> 我已经对您链接的问题发表了评论，并且您可能已经看到，这是一个 melonDS 问题。它将在下一个版本中修复。同时，您可以尝试使用可在此处找到的每晚构建：[https ://github.com/rafaelvcaetano/melonDS-android/actions/workflows/main.yaml](https://github.com/rafaelvcaetano/melonDS-android/actions/workflows/main.yaml)

thanks, melonds android is excellent, i like it so much

**Comment by crhhahaha** [comment]
I also hope that melonds can make the gba card slot work, like this one, he has the gba.bin file, I don't know if this function can be implemented?

https://user-images.githubusercontent.com/87603208/190927551-f10c64e3-f608-4904-86d2-68e66212768b.mp4
![31e0aef67824228948b8ec0a8f8e889](https://user-images.githubusercontent.com/87603208/190927555-f0da8757-6cb8-4a6d-b7b0-cd715912af18.jpg)

**Comment by rafaelvcaetano** [comment]
Unfortunately, that is out of the scope of this project. However, if you have DS games that interact with GBA cartridges (like, for example, some Pokémon games), that is already supported. You just need to click the gear icon of the desired ROM, enable the "Load GBA ROM" switch and select the ROM and save file.

![image](https://user-images.githubusercontent.com/9086379/190927646-d6acfeca-b030-4224-8879-2f1d13ee1705.png)

**Comment by crhhahaha** [comment]
> 不幸的是，这超出了本项目的范围。但是，如果您有与 GBA 卡带交互的 DS 游戏（例如，某些 Pokémon 游戏），则已经支持。您只需单击所需ROM的齿轮图标，启用“加载GBA ROM”开关并选择ROM并保存文件。
> 
> ![图片](https://user-images.githubusercontent.com/9086379/190927646-d6acfeca-b030-4224-8879-2f1d13ee1705.png)

 Thanks for your works，i got it
