### ISSUE TITLE
Update to 0.9.4?

### ISSUE THREAD

**Issue by FerLuisxd** [rafaelvcaetano/melonDS-android#980]
MelonDS has been updated to 0.9.4 maybe that can be done here as well?

**Comment by rafaelvcaetano** [comment]
I've already updated it to 0.9.4 but I haven't released an update with it. You can try the latest development build to test it. You can find development builds here: https://github.com/rafaelvcaetano/melonDS-android/actions/workflows/main.yaml
Just select the latest build, then scroll to the bottom to the "Artifacts" section where you can find the APK.
